/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.UsuarioController;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author enriq
 */
public class panelUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form panelArticulos
     */
    UsuarioController usuarioController=new UsuarioController();
    Map<String, Object>[] tabla;
    boolean editNuevo;
    int idSeleccionado;
    private JDialog dialog;
    public panelUsuarios() {
        initComponents();
        iniComplementLayout();
        iniSize();
        iniDiseños();
        iniTablaUsuarios();
        iniComboBoxRol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneContenidoUsuarios = new javax.swing.JPanel();
        paneCrudUsuarios = new javax.swing.JPanel();
        paneTituloUsuarios = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblTituloIconArticulos = new javax.swing.JLabel();
        paneContenedor = new javax.swing.JPanel();
        paneOpcionesUsuarios = new javax.swing.JPanel();
        paneBuscar = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        lblTituloIconArticulos1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblTituloIconArticulos2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JPanel();
        lblTituloIconArticulos3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paneTablaUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        paneModalUsuarios = new javax.swing.JPanel();
        paneContenidoVentana = new javax.swing.JPanel();
        paneAtributosUsuario = new javax.swing.JPanel();
        paneRol = new javax.swing.JPanel();
        lblRol = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        paneUsuario = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        paneNombre = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        paneClave = new javax.swing.JPanel();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        paneBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        paneHeader = new javax.swing.JPanel();
        lblHeaderLogo = new javax.swing.JLabel();
        paneHeaderOpciones = new javax.swing.JPanel();
        lblCerrarVentana = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneContenidoUsuarios.setBackground(new java.awt.Color(229, 238, 255));

        paneCrudUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        paneCrudUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 4));

        paneTituloUsuarios.setBackground(new java.awt.Color(72, 84, 247));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuarios");

        lblTituloIconArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuarios.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloUsuariosLayout = new javax.swing.GroupLayout(paneTituloUsuarios);
        paneTituloUsuarios.setLayout(paneTituloUsuariosLayout);
        paneTituloUsuariosLayout.setHorizontalGroup(
            paneTituloUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloUsuariosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTituloIconArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloUsuariosLayout.setVerticalGroup(
            paneTituloUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneContenedor.setBackground(new java.awt.Color(153, 153, 153));

        paneOpcionesUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        paneBuscar.setBackground(new java.awt.Color(72, 84, 247));
        paneBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 3));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(72, 84, 247));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneBuscarLayout = new javax.swing.GroupLayout(paneBuscar);
        paneBuscar.setLayout(paneBuscarLayout);
        paneBuscarLayout.setHorizontalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        paneBuscarLayout.setVerticalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnEditar.setBackground(new java.awt.Color(255, 214, 0));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        lblTituloIconArticulos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapizB.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloIconArticulos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGroup(btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloIconArticulos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btnEditarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(211, 80, 80));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarMouseMoved(evt);
            }
        });
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        lblTituloIconArticulos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basuraB.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTituloIconArticulos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnEliminarLayout.createSequentialGroup()
                        .addComponent(lblTituloIconArticulos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))))
        );

        btnNuevo.setBackground(new java.awt.Color(0, 197, 26));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNuevoMouseMoved(evt);
            }
        });
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoMouseExited(evt);
            }
        });

        lblTituloIconArticulos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoB.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo");

        javax.swing.GroupLayout btnNuevoLayout = new javax.swing.GroupLayout(btnNuevo);
        btnNuevo.setLayout(btnNuevoLayout);
        btnNuevoLayout.setHorizontalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNuevoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloIconArticulos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnNuevoLayout.setVerticalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneOpcionesUsuariosLayout = new javax.swing.GroupLayout(paneOpcionesUsuarios);
        paneOpcionesUsuarios.setLayout(paneOpcionesUsuariosLayout);
        paneOpcionesUsuariosLayout.setHorizontalGroup(
            paneOpcionesUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOpcionesUsuariosLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        paneOpcionesUsuariosLayout.setVerticalGroup(
            paneOpcionesUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOpcionesUsuariosLayout.createSequentialGroup()
                .addGroup(paneOpcionesUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        paneTablaUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout paneTablaUsuariosLayout = new javax.swing.GroupLayout(paneTablaUsuarios);
        paneTablaUsuarios.setLayout(paneTablaUsuariosLayout);
        paneTablaUsuariosLayout.setHorizontalGroup(
            paneTablaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        paneTablaUsuariosLayout.setVerticalGroup(
            paneTablaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneContenedorLayout = new javax.swing.GroupLayout(paneContenedor);
        paneContenedor.setLayout(paneContenedorLayout);
        paneContenedorLayout.setHorizontalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneTablaUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneOpcionesUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneContenedorLayout.setVerticalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addComponent(paneOpcionesUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(paneTablaUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneCrudUsuariosLayout = new javax.swing.GroupLayout(paneCrudUsuarios);
        paneCrudUsuarios.setLayout(paneCrudUsuariosLayout);
        paneCrudUsuariosLayout.setHorizontalGroup(
            paneCrudUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneCrudUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneCrudUsuariosLayout.setVerticalGroup(
            paneCrudUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCrudUsuariosLayout.createSequentialGroup()
                .addComponent(paneTituloUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoUsuariosLayout = new javax.swing.GroupLayout(paneContenidoUsuarios);
        paneContenidoUsuarios.setLayout(paneContenidoUsuariosLayout);
        paneContenidoUsuariosLayout.setHorizontalGroup(
            paneContenidoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoUsuariosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(paneCrudUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        paneContenidoUsuariosLayout.setVerticalGroup(
            paneContenidoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoUsuariosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(paneCrudUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        paneModalUsuarios.setBackground(new java.awt.Color(255, 255, 255));

        paneContenidoVentana.setOpaque(false);

        paneAtributosUsuario.setBackground(new java.awt.Color(204, 204, 204));
        paneAtributosUsuario.setOpaque(false);

        paneRol.setOpaque(false);

        lblRol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRol.setText("Rol");

        cbxRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneRolLayout = new javax.swing.GroupLayout(paneRol);
        paneRol.setLayout(paneRolLayout);
        paneRolLayout.setHorizontalGroup(
            paneRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRolLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(paneRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRol)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        paneRolLayout.setVerticalGroup(
            paneRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRolLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        paneUsuario.setOpaque(false);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneUsuarioLayout = new javax.swing.GroupLayout(paneUsuario);
        paneUsuario.setLayout(paneUsuarioLayout);
        paneUsuarioLayout.setHorizontalGroup(
            paneUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUsuarioLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(paneUsuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneUsuarioLayout.setVerticalGroup(
            paneUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUsuarioLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        paneNombre.setOpaque(false);

        txtnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnombre.setText("Nombre Completo");

        javax.swing.GroupLayout paneNombreLayout = new javax.swing.GroupLayout(paneNombre);
        paneNombre.setLayout(paneNombreLayout);
        paneNombreLayout.setHorizontalGroup(
            paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNombreLayout.createSequentialGroup()
                .addGroup(paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneNombreLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblnombre))
                    .addGroup(paneNombreLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneNombreLayout.setVerticalGroup(
            paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNombreLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneClave.setOpaque(false);

        lblClave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClave.setText("Contraseña");

        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClave.setToolTipText("");

        javax.swing.GroupLayout paneClaveLayout = new javax.swing.GroupLayout(paneClave);
        paneClave.setLayout(paneClaveLayout);
        paneClaveLayout.setHorizontalGroup(
            paneClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneClaveLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(paneClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClave)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        paneClaveLayout.setVerticalGroup(
            paneClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneClaveLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneAtributosUsuarioLayout = new javax.swing.GroupLayout(paneAtributosUsuario);
        paneAtributosUsuario.setLayout(paneAtributosUsuarioLayout);
        paneAtributosUsuarioLayout.setHorizontalGroup(
            paneAtributosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAtributosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneAtributosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(paneNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(paneAtributosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        paneAtributosUsuarioLayout.setVerticalGroup(
            paneAtributosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAtributosUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );

        paneBotones.setOpaque(false);

        btnCancelar.setBackground(new java.awt.Color(102, 102, 255));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCancelarMouseMoved(evt);
            }
        });
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(102, 102, 255));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnGuardarMouseMoved(evt);
            }
        });
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoVentanaLayout = new javax.swing.GroupLayout(paneContenidoVentana);
        paneContenidoVentana.setLayout(paneContenidoVentanaLayout);
        paneContenidoVentanaLayout.setHorizontalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneAtributosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        paneContenidoVentanaLayout.setVerticalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(paneAtributosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        paneHeader.setBackground(new java.awt.Color(25, 34, 143));

        lblHeaderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        paneHeaderOpciones.setBackground(new java.awt.Color(27, 39, 187));
        paneHeaderOpciones.setOpaque(false);

        lblCerrarVentana.setBackground(new java.awt.Color(255, 58, 97));
        lblCerrarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarVentana.png"))); // NOI18N
        lblCerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseMoved(evt);
            }
        });
        lblCerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneHeaderOpcionesLayout = new javax.swing.GroupLayout(paneHeaderOpciones);
        paneHeaderOpciones.setLayout(paneHeaderOpcionesLayout);
        paneHeaderOpcionesLayout.setHorizontalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderOpcionesLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(lblCerrarVentana)
                .addGap(48, 48, 48))
        );
        paneHeaderOpcionesLayout.setVerticalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderOpcionesLayout.createSequentialGroup()
                .addComponent(lblCerrarVentana)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Nuevo Usuario");
        lbltitulo.setToolTipText("");

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHeaderLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHeaderLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                        .addComponent(lbltitulo)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout paneModalUsuariosLayout = new javax.swing.GroupLayout(paneModalUsuarios);
        paneModalUsuarios.setLayout(paneModalUsuariosLayout);
        paneModalUsuariosLayout.setHorizontalGroup(
            paneModalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
            .addGroup(paneModalUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneModalUsuariosLayout.setVerticalGroup(
            paneModalUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModalUsuariosLayout.createSequentialGroup()
                .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paneContenidoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(paneModalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneContenidoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(paneModalUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        // TODO add your handling code here:
        Color Micolor= new Color(0,0,204);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        Color Micolor= new Color(72,84,247);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
        // TODO add your handling code here:
         btnEditar.setBackground(new Color(255,227,82)); 
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
         btnEditar.setBackground(new Color(255,214,0)); 
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseMoved
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(249,98,98));
    }//GEN-LAST:event_btnEliminarMouseMoved

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(228,77,77));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnNuevoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseMoved
        // TODO add your handling code here:
        btnNuevo.setBackground(new Color(0,222,29));
    }//GEN-LAST:event_btnNuevoMouseMoved

    private void btnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseExited
        // TODO add your handling code here:
        btnNuevo.setBackground(new Color(0,197,26)); 
    }//GEN-LAST:event_btnNuevoMouseExited

    private void lblCerrarVentanaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseMoved
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(true);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseMoved

    private void lblCerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseClicked
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtnombre.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
    }//GEN-LAST:event_lblCerrarVentanaMouseClicked

    private void lblCerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseExited
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseExited

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        // TODO add your handling code here:
        editNuevo=true;
        NuevoModalUsuarios();
        dialog.setLocationRelativeTo(null); // centra el dialogo en la pantalla
        dialog.setVisible(true);
        
        
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseMoved
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(62,62,241)); 
    }//GEN-LAST:event_btnGuardarMouseMoved

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(102,102,255)); 
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseMoved
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(62,62,241)); 
    }//GEN-LAST:event_btnCancelarMouseMoved

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255)); 
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255)); 
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtnombre.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(102,102,255));
       
        if(editNuevo){
            Guardar();
        }else{
            Editar(idSeleccionado);
        }
        
        txtnombre.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        iniTablaUsuarios();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        TableModel model = tblUsuarios.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblUsuarios.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            // Obtiene los valores de las columnas de la fila seleccionada
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna
            Object value2 = model.getValueAt(selectedRow, 1); // Valor de la primera columna
            Object value3 = model.getValueAt(selectedRow, 2); // Valor de la primera columna
            Object value4 = model.getValueAt(selectedRow, 3); // Valor de la primera columna
            Object value5 = model.getValueAt(selectedRow, 4); // Valor de la primera columna
            
            int idUsuario = Integer.parseInt(value1.toString());
            
            txtUsuario.setText(value2.toString());
            txtnombre.setText(value3.toString());
            txtClave.setText(value4.toString());
            for (int i = 0; i < cbxRol.getItemCount(); i++) {
                String elemento = cbxRol.getItemAt(i);
                if (elemento.equals(value5.toString())) {
                    // Se encontró el elemento con el nombre deseado, se selecciona
                    cbxRol.setSelectedIndex(i);
                    break;
                }
            }
            
            idSeleccionado=idUsuario;
            editNuevo=false;
            EditarModalUsuarios();
            dialog.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialog.setVisible(true);
            
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        TableModel model = tblUsuarios.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblUsuarios.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna   
            int idUsuario = Integer.parseInt(value1.toString());
            
            Eliminar(idUsuario);
            
        }
        iniTablaUsuarios();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        iniTablaUsuarios();
       String elementoBusqueda = txtBusqueda.getText(); // Elemento que se desea buscar
        if(!elementoBusqueda.equals("")){
            DefaultTableModel model = (DefaultTableModel) tblUsuarios.getModel();
            int rowCount = model.getRowCount();
            int columnCount = model.getColumnCount();

            List<Integer> filasCoincidentes = new ArrayList<>();

            for (int row = 0; row < rowCount; row++) {
                for (int column = 0; column < columnCount; column++) {
                    Object cellValue = model.getValueAt(row, column);
                    String cellString = String.valueOf(cellValue);

                    if (cellString.equals(elementoBusqueda)) {
                        filasCoincidentes.add(row);
                        // Puedes realizar alguna acción adicional, como resaltar la fila
                    }
                }
            }
            DefaultTableModel modelUsuario = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            modelUsuario.addColumn("Id");
            modelUsuario.addColumn("Usuario");
            modelUsuario.addColumn("Nombre");
            modelUsuario.addColumn("Contraseña");
            modelUsuario.addColumn("Rol");
            modelUsuario.addColumn("Cantidad de Ventas");

            for (Integer filaCoincidente : filasCoincidentes) {
                Object[] rowData = new Object[6];
                rowData[0] = tblUsuarios.getValueAt(filaCoincidente, 0);  
                rowData[1] = tblUsuarios.getValueAt(filaCoincidente, 1);  
                rowData[2] = tblUsuarios.getValueAt(filaCoincidente, 2);  
                rowData[3] = tblUsuarios.getValueAt(filaCoincidente, 3);  
                rowData[4] = tblUsuarios.getValueAt(filaCoincidente, 4);  
                rowData[5] = tblUsuarios.getValueAt(filaCoincidente, 5); 
 
                modelUsuario.addRow(rowData);
            }
      
            tblUsuarios.setModel(modelUsuario);
            tblUsuarios.repaint();
        }else{
            iniTablaUsuarios();
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnNuevo;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrarVentana;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblHeaderLogo;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTituloIconArticulos;
    private javax.swing.JLabel lblTituloIconArticulos1;
    private javax.swing.JLabel lblTituloIconArticulos2;
    private javax.swing.JLabel lblTituloIconArticulos3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel paneAtributosUsuario;
    private javax.swing.JPanel paneBotones;
    private javax.swing.JPanel paneBuscar;
    private javax.swing.JPanel paneClave;
    private javax.swing.JPanel paneContenedor;
    private javax.swing.JPanel paneContenidoUsuarios;
    private javax.swing.JPanel paneContenidoVentana;
    private javax.swing.JPanel paneCrudUsuarios;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JPanel paneHeaderOpciones;
    private javax.swing.JPanel paneModalUsuarios;
    private javax.swing.JPanel paneNombre;
    private javax.swing.JPanel paneOpcionesUsuarios;
    private javax.swing.JPanel paneRol;
    private javax.swing.JPanel paneTablaUsuarios;
    private javax.swing.JPanel paneTituloUsuarios;
    private javax.swing.JPanel paneUsuario;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    private void iniComplementLayout() {
        getContentPane().setLayout(new CardLayout());
        
        getContentPane().add(paneContenidoUsuarios);
        getContentPane().remove(paneModalUsuarios);
        //layaout para el contenido
        FlowLayout flowlayoutContenido = new FlowLayout(FlowLayout.CENTER,10,70);
        paneContenidoUsuarios.setLayout(flowlayoutContenido);
            FlowLayout flowlayoutTituloArticulos = new FlowLayout(FlowLayout.LEFT,10,10);
            paneCrudUsuarios.setLayout(new BorderLayout());
                paneTituloUsuarios.setLayout(flowlayoutTituloArticulos);
                paneCrudUsuarios.add(paneTituloUsuarios, java.awt.BorderLayout.PAGE_START);
                paneCrudUsuarios.add(paneContenedor, java.awt.BorderLayout.CENTER);
                    paneContenedor.setLayout(new BorderLayout());
                    paneContenedor.add(paneOpcionesUsuarios, java.awt.BorderLayout.PAGE_START);
                    paneContenedor.add(paneTablaUsuarios, java.awt.BorderLayout.CENTER);
                    
                FlowLayout flowlayoutOpArticulos= new FlowLayout(FlowLayout.RIGHT,15,30);
                paneOpcionesUsuarios.setLayout(flowlayoutOpArticulos);
                    FlowLayout flowlayoutBoton = new FlowLayout(FlowLayout.CENTER,10,8);
                    paneBuscar.setLayout(new BoxLayout(paneBuscar, BoxLayout.X_AXIS));
                    btnNuevo.setLayout(flowlayoutBoton);
                    btnEditar.setLayout(flowlayoutBoton);
                    btnEliminar.setLayout(flowlayoutBoton);
        
        
                    
                    
       //modal nuevo
        //layout de la ventana  
         paneModalUsuarios.setLayout(new BorderLayout());

         paneModalUsuarios.add(paneContenidoVentana, java.awt.BorderLayout.CENTER);
         paneModalUsuarios.add(paneHeader, java.awt.BorderLayout.PAGE_START);

          //layout de header de la ventana
         paneHeader.setLayout(new BoxLayout(paneHeader, BoxLayout.X_AXIS));

         FlowLayout flowlayoutHeaderOpciones = new FlowLayout(FlowLayout.RIGHT,0,0);
         paneHeaderOpciones.setLayout(flowlayoutHeaderOpciones);
         paneHeader.add(lblHeaderLogo);
         paneHeader.add(lbltitulo);
         paneHeader.add(Box.createHorizontalGlue()); // Espaciador flexible
         paneHeader.add(paneHeaderOpciones);
         //contenido del modal
         
         //contenerdo de los atributos
         paneContenidoVentana.setLayout(new BorderLayout());
         paneContenidoVentana.add(paneAtributosUsuario, java.awt.BorderLayout.CENTER);
         paneContenidoVentana.add(paneBotones, java.awt.BorderLayout.PAGE_END);
         FlowLayout flowlayoutAtributosUsuario = new FlowLayout(FlowLayout.CENTER,10,30);
         paneAtributosUsuario.setLayout(flowlayoutAtributosUsuario);
            //contenedor de los txt y label
            paneNombre.setLayout(new BoxLayout(paneNombre, BoxLayout.Y_AXIS));
                txtnombre.setAlignmentX(LEFT_ALIGNMENT);
                lblnombre.setAlignmentX(LEFT_ALIGNMENT);
                paneNombre.add(lblnombre);     
                paneNombre.add(txtnombre); 
            paneUsuario.setLayout(new BoxLayout(paneUsuario, BoxLayout.Y_AXIS));
                txtUsuario.setAlignmentX(LEFT_ALIGNMENT);
                lblUsuario.setAlignmentX(LEFT_ALIGNMENT);
                paneUsuario.add(lblUsuario);     
                paneUsuario.add(txtUsuario); 
            paneRol.setLayout(new BoxLayout(paneRol, BoxLayout.Y_AXIS));
                cbxRol.setAlignmentX(LEFT_ALIGNMENT);
                lblRol.setAlignmentX(LEFT_ALIGNMENT);
                paneRol.add(lblRol);     
                paneRol.add(cbxRol); 
            paneClave.setLayout(new BoxLayout(paneClave, BoxLayout.Y_AXIS));
                txtClave.setAlignmentX(LEFT_ALIGNMENT);
                lblClave.setAlignmentX(LEFT_ALIGNMENT);
                paneClave.add(lblClave);     
                paneClave.add(txtClave); 
        paneAtributosUsuario.add(paneNombre);
        paneAtributosUsuario.add(paneUsuario);
        paneAtributosUsuario.add(paneRol);
        paneAtributosUsuario.add(paneClave);
        
        
        FlowLayout flowlayoutBotones = new FlowLayout(FlowLayout.CENTER,30,10);
        paneBotones.setLayout(flowlayoutBotones);
        btnGuardar.setLayout(new GridBagLayout());
        btnCancelar.setLayout(new GridBagLayout());
    }

    private void iniSize() {
         //tamaño de ventana
        this.setBounds(0,0,1400, 900);
        
        //tamaño del panel de contenido
        paneContenidoUsuarios.setPreferredSize(new Dimension( 1, 1));    
            paneCrudUsuarios.setPreferredSize(new Dimension( 1000, 650));    
                paneOpcionesUsuarios.setPreferredSize(new Dimension( 1000, 100));  
                //paneTablaArticulos.setPreferredSize(new Dimension( 1000, 100));  
                    txtBusqueda.setPreferredSize(new Dimension( 200, 40));
                    btnBuscar.setPreferredSize(new Dimension( 60, 40));
                    btnNuevo.setPreferredSize(new Dimension( 200, 40));
                    btnEditar.setPreferredSize(new Dimension( 200, 40));
                    btnEliminar.setPreferredSize(new Dimension( 200, 40));
                    
        //modal
            //tamaño del panel header
            paneHeader.setPreferredSize(new Dimension( 1, 40));
            lblHeaderLogo.setSize(new Dimension( 40, 40));
            lblCerrarVentana.setPreferredSize(new Dimension( 40, 40));
            
            //tamaño del contenido
            paneAtributosUsuario.setPreferredSize(new Dimension(380,60));
            paneNombre.setPreferredSize(new Dimension(380,60));
            paneUsuario.setPreferredSize(new Dimension(380,60));
            paneRol.setPreferredSize(new Dimension(380,60));
            paneClave.setPreferredSize(new Dimension(380,60));
            
            paneBotones.setPreferredSize(new Dimension(450,100));
            btnGuardar.setPreferredSize(new Dimension(150,40));
            btnCancelar.setPreferredSize(new Dimension(150,40));
    }           


    private void iniDiseños() {
        //modal
            //inicaiar imagenes del Header de la ventana.
            redimencionarImagenen(lblHeaderLogo,"/img/logo.png");       
            lblCerrarVentana.setVerticalAlignment(SwingConstants.CENTER);
            lblCerrarVentana.setHorizontalAlignment(SwingConstants.CENTER);
    }
    public JPanel obtenerPanel(){
        return this.paneContenidoUsuarios;
    }
     public void redimencionarImagenen(JLabel lblicon,String img){
      // Cargamos la imagen desde un archivo
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource(img));//"/Img/login2.jpg"

        // Ajustamos el tamaño de la imagen al tamaño del JLabel
        Image image = icon.getImage();
        Image scaledImage = image.getScaledInstance(lblicon.getWidth(), lblicon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Establecemos la imagen en el JLabel                
            
        ///labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.jpg"))); 
        lblicon.setIcon(scaledIcon);    
    }
    private void NuevoModalUsuarios(){
        lbltitulo.setText("Nuevo Usuario");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalUsuarios); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,550)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    private void EditarModalUsuarios(){
        
        lbltitulo.setText("Modificar Usuario");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalUsuarios); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,550)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    private void iniTablaUsuarios(){
        tabla = usuarioController.ObtenerUsuarios();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("Id");
        model.addColumn("Usuario");
        model.addColumn("Nombre");
        model.addColumn("Contraseña");
        model.addColumn("Rol");
        model.addColumn("Cantidad de Ventas");

        for(Map<String, Object> res : tabla){
            model.addRow(new Object[]{res.get("id"), res.get("usuario"),res.get("nombre"),res.get("password"),res.get("rol"),res.get("cantVenta")});        
        } 
        
        tblUsuarios.setModel(model);
        tblUsuarios.repaint();
    }
    private void iniComboBoxRol(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("EmpleadoVentas");      
        model.addElement("EmpleadoCompras");    
        model.addElement("EmpleadoAlmacen");    
        model.addElement("Supervisor");    
        
        cbxRol.setModel(model);
        
    }
    private void Guardar(){
        String rol=cbxRol.getSelectedItem().toString();
        String nombre=txtnombre.getText();
        String usuario= txtUsuario.getText();
        String Contraseña= txtClave.getText();
                
        if(usuarioController.registrarUsuario(nombre, usuario, rol, Contraseña)){
            ModalNotificar modal = new ModalNotificar("Guardado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
    }
    private void Editar(int id){
        String rol=cbxRol.getSelectedItem().toString();
        String nombre=txtnombre.getText();
        String usuario= txtUsuario.getText();
        String Contraseña= txtClave.getText();


        if(usuarioController.actualizarUsuario(id,nombre, usuario, rol, Contraseña)){
            ModalNotificar modal = new ModalNotificar("Actualizado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
        
    }
    private void Eliminar(int id){

        if(usuarioController.EliminarUsuario(id)){
            ModalNotificar modal = new ModalNotificar("Eliminado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
        
    }
}
