/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author enriq
 */
public class panelPerfil extends javax.swing.JFrame {

    /**
     * Creates new form panelArticulos
     */
    public panelPerfil() {
        initComponents();
        iniComplementLayout();
        iniSize();
        iniDiseños();
        iniLocation();
        iniDatosPerfil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        paneContenidoPerfil = new javax.swing.JPanel();
        paneDatosPerfil = new javax.swing.JPanel();
        paneTituloPerfil = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblTituloIconArticulos = new javax.swing.JLabel();
        paneContenedor = new javax.swing.JPanel();
        lblimgperfil = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();
        lblusuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblcantventas = new javax.swing.JLabel();
        txtcantventas = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneContenidoPerfil.setBackground(new java.awt.Color(229, 238, 255));

        paneDatosPerfil.setBackground(new java.awt.Color(255, 255, 255));
        paneDatosPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 4));

        paneTituloPerfil.setBackground(new java.awt.Color(72, 84, 247));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Perfil");

        lblTituloIconArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloPerfilLayout = new javax.swing.GroupLayout(paneTituloPerfil);
        paneTituloPerfil.setLayout(paneTituloPerfilLayout);
        paneTituloPerfilLayout.setHorizontalGroup(
            paneTituloPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloPerfilLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTituloIconArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloPerfilLayout.setVerticalGroup(
            paneTituloPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneContenedor.setBackground(new java.awt.Color(255, 255, 255));

        lblimgperfil.setBackground(new java.awt.Color(204, 204, 204));
        lblimgperfil.setOpaque(true);

        lblnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblnombre.setText("Nombre Completo");

        txtnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtnombre.setEnabled(false);

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRol.setText("Rol");

        txtRol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRol.setEnabled(false);

        lblusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblusuario.setText("Usuario");

        txtusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtusuario.setEnabled(false);

        lblcantventas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblcantventas.setText("Cantidad de Ventas");

        txtcantventas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcantventas.setEnabled(false);

        javax.swing.GroupLayout paneContenedorLayout = new javax.swing.GroupLayout(paneContenedor);
        paneContenedor.setLayout(paneContenedorLayout);
        paneContenedorLayout.setHorizontalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addGroup(paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneContenedorLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRol)
                            .addComponent(lblnombre)
                            .addComponent(lblusuario)
                            .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                            .addComponent(txtcantventas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblcantventas)
                            .addComponent(txtRol)
                            .addComponent(txtnombre)))
                    .addGroup(paneContenedorLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblimgperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        paneContenedorLayout.setVerticalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblimgperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblcantventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcantventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneDatosPerfilLayout = new javax.swing.GroupLayout(paneDatosPerfil);
        paneDatosPerfil.setLayout(paneDatosPerfilLayout);
        paneDatosPerfilLayout.setHorizontalGroup(
            paneDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneDatosPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneDatosPerfilLayout.setVerticalGroup(
            paneDatosPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneDatosPerfilLayout.createSequentialGroup()
                .addComponent(paneTituloPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout paneContenidoPerfilLayout = new javax.swing.GroupLayout(paneContenidoPerfil);
        paneContenidoPerfil.setLayout(paneContenidoPerfilLayout);
        paneContenidoPerfilLayout.setHorizontalGroup(
            paneContenidoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoPerfilLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(paneDatosPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        paneContenidoPerfilLayout.setVerticalGroup(
            paneContenidoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoPerfilLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(paneDatosPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(881, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneContenidoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTituloIconArticulos;
    private javax.swing.JLabel lblcantventas;
    private javax.swing.JLabel lblimgperfil;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel paneContenedor;
    private javax.swing.JPanel paneContenidoPerfil;
    private javax.swing.JPanel paneDatosPerfil;
    private javax.swing.JPanel paneTituloPerfil;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtcantventas;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    private void iniComplementLayout() {
        getContentPane().setLayout(new CardLayout());
        
        getContentPane().add(paneContenidoPerfil);
        //layaout para el contenido
        FlowLayout flowlayoutContenido = new FlowLayout(FlowLayout.CENTER,30,50);
        paneContenidoPerfil.setLayout(flowlayoutContenido);
            FlowLayout flowlayoutTituloArticulos = new FlowLayout(FlowLayout.LEFT,10,10);
            paneDatosPerfil.setLayout(new BorderLayout());
                paneTituloPerfil.setLayout(flowlayoutTituloArticulos);
                paneDatosPerfil.add(paneTituloPerfil, java.awt.BorderLayout.PAGE_START);
                paneDatosPerfil.add(paneContenedor, java.awt.BorderLayout.CENTER);
                
                    paneContenedor.setLayout(null);

                    
                    
                    
       
        
        
    }

    private void iniSize() {
         //tamaño de ventana
        this.setBounds(0,0,1400, 900);
        
        //tamaño del panel de contenido
        paneContenidoPerfil.setPreferredSize(new Dimension( 1, 1));    
            paneDatosPerfil.setPreferredSize(new Dimension( 570, 650)); 
            paneContenedor.setPreferredSize(new Dimension( 570, 500)); 
            //contenido del perfil
                lblimgperfil.setPreferredSize(new Dimension( 110, 110));
                txtnombre.setPreferredSize(new Dimension( 500, 31));
                txtusuario.setPreferredSize(new Dimension( 500, 31));
                txtRol.setPreferredSize(new Dimension( 500, 31));
                txtcantventas.setPreferredSize(new Dimension( 500, 31));
               
    }

    public void redimencionarImagenen(JLabel lblicon,String img){
      // Cargamos la imagen desde un archivo
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource(img));//"/Img/login2.jpg"

        // Ajustamos el tamaño de la imagen al tamaño del JLabel
        Image image = icon.getImage();
        Image scaledImage = image.getScaledInstance(lblicon.getWidth(), lblicon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Establecemos la imagen en el JLabel                
            
        ///labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.jpg"))); 
        lblicon.setIcon(scaledIcon);    
    }
    private void iniDiseños() {
        //cargar y redimencionar imagen del perfil
        redimencionarImagenen(lblimgperfil, "/img/imgPerfil.png");
    }

    private void iniLocation() {
        lblimgperfil.setLocation(230, 30);
        lblnombre.setLocation(35, 190);
        txtnombre.setLocation(35, 225);
        lblusuario.setLocation(35, 286);
        txtusuario.setLocation(35, 321);
        lblRol.setLocation(35, 382);
        txtRol.setLocation(35, 417);
        lblcantventas.setLocation(35, 478);
        txtcantventas.setLocation(35, 513);
    }
   public JPanel obtenerPanel(){
        return this.paneContenidoPerfil;
    }
    private void iniDatosPerfil(){
        txtnombre.setText((String)LoginFrame.sesionUsuario.get("nombre"));
        txtusuario.setText((String)LoginFrame.sesionUsuario.get("usuario"));
        txtRol.setText((String)LoginFrame.sesionUsuario.get("rol"));
        txtcantventas.setText(LoginFrame.sesionUsuario.get("cantVenta").toString());
        
    }
}
