/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.ProveedoresController;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author enriq
 */
public class panelProveedores extends javax.swing.JFrame {

    /**
     * Creates new form panelArticulos
     */
    ProveedoresController proveedoresController=new ProveedoresController();
    Map<String, Object>[] tabla;
    boolean editNuevo;
    int idSeleccionado;
    private JDialog dialog;
    public panelProveedores() {
        initComponents();
        iniComplementLayout();
        iniSize();
        iniDiseños();
        iniTablaProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneContenidoProveedores = new javax.swing.JPanel();
        paneCrudProveedores = new javax.swing.JPanel();
        paneTituloProveedores = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblTituloIconArticulos = new javax.swing.JLabel();
        paneContenedor = new javax.swing.JPanel();
        paneOpcionesProveedores = new javax.swing.JPanel();
        paneBuscar = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        lblTituloIconArticulos1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblTituloIconArticulos2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JPanel();
        lblTituloIconArticulos3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paneTablaProveedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        paneModalProveedor = new javax.swing.JPanel();
        paneContenidoVentana = new javax.swing.JPanel();
        paneAtributosProveedor = new javax.swing.JPanel();
        paneTelefono = new javax.swing.JPanel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        paneNombre = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        paneDireccion = new javax.swing.JPanel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        paneRuc = new javax.swing.JPanel();
        txtRuc = new javax.swing.JTextField();
        lblRuc = new javax.swing.JLabel();
        paneBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        paneHeader = new javax.swing.JPanel();
        lblHeaderLogo = new javax.swing.JLabel();
        paneHeaderOpciones = new javax.swing.JPanel();
        lblCerrarVentana = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneContenidoProveedores.setBackground(new java.awt.Color(229, 238, 255));

        paneCrudProveedores.setBackground(new java.awt.Color(255, 255, 255));
        paneCrudProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 4));

        paneTituloProveedores.setBackground(new java.awt.Color(72, 84, 247));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Proveedores");

        lblTituloIconArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedores.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloProveedoresLayout = new javax.swing.GroupLayout(paneTituloProveedores);
        paneTituloProveedores.setLayout(paneTituloProveedoresLayout);
        paneTituloProveedoresLayout.setHorizontalGroup(
            paneTituloProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloProveedoresLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTituloIconArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloProveedoresLayout.setVerticalGroup(
            paneTituloProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneContenedor.setBackground(new java.awt.Color(153, 153, 153));

        paneOpcionesProveedores.setBackground(new java.awt.Color(255, 255, 255));

        paneBuscar.setBackground(new java.awt.Color(72, 84, 247));
        paneBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 3));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(72, 84, 247));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneBuscarLayout = new javax.swing.GroupLayout(paneBuscar);
        paneBuscar.setLayout(paneBuscarLayout);
        paneBuscarLayout.setHorizontalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        paneBuscarLayout.setVerticalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnEditar.setBackground(new java.awt.Color(255, 214, 0));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        lblTituloIconArticulos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapizB.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloIconArticulos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGroup(btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloIconArticulos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btnEditarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(211, 80, 80));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarMouseMoved(evt);
            }
        });
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        lblTituloIconArticulos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basuraB.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTituloIconArticulos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnEliminarLayout.createSequentialGroup()
                        .addComponent(lblTituloIconArticulos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))))
        );

        btnNuevo.setBackground(new java.awt.Color(0, 197, 26));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNuevoMouseMoved(evt);
            }
        });
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoMouseExited(evt);
            }
        });

        lblTituloIconArticulos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoB.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo");

        javax.swing.GroupLayout btnNuevoLayout = new javax.swing.GroupLayout(btnNuevo);
        btnNuevo.setLayout(btnNuevoLayout);
        btnNuevoLayout.setHorizontalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNuevoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloIconArticulos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnNuevoLayout.setVerticalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneOpcionesProveedoresLayout = new javax.swing.GroupLayout(paneOpcionesProveedores);
        paneOpcionesProveedores.setLayout(paneOpcionesProveedoresLayout);
        paneOpcionesProveedoresLayout.setHorizontalGroup(
            paneOpcionesProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOpcionesProveedoresLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        paneOpcionesProveedoresLayout.setVerticalGroup(
            paneOpcionesProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOpcionesProveedoresLayout.createSequentialGroup()
                .addGroup(paneOpcionesProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        paneTablaProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProveedores);

        javax.swing.GroupLayout paneTablaProveedoresLayout = new javax.swing.GroupLayout(paneTablaProveedores);
        paneTablaProveedores.setLayout(paneTablaProveedoresLayout);
        paneTablaProveedoresLayout.setHorizontalGroup(
            paneTablaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        paneTablaProveedoresLayout.setVerticalGroup(
            paneTablaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneContenedorLayout = new javax.swing.GroupLayout(paneContenedor);
        paneContenedor.setLayout(paneContenedorLayout);
        paneContenedorLayout.setHorizontalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneTablaProveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneOpcionesProveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneContenedorLayout.setVerticalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addComponent(paneOpcionesProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(paneTablaProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneCrudProveedoresLayout = new javax.swing.GroupLayout(paneCrudProveedores);
        paneCrudProveedores.setLayout(paneCrudProveedoresLayout);
        paneCrudProveedoresLayout.setHorizontalGroup(
            paneCrudProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneCrudProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneCrudProveedoresLayout.setVerticalGroup(
            paneCrudProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCrudProveedoresLayout.createSequentialGroup()
                .addComponent(paneTituloProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoProveedoresLayout = new javax.swing.GroupLayout(paneContenidoProveedores);
        paneContenidoProveedores.setLayout(paneContenidoProveedoresLayout);
        paneContenidoProveedoresLayout.setHorizontalGroup(
            paneContenidoProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoProveedoresLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(paneCrudProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneContenidoProveedoresLayout.setVerticalGroup(
            paneContenidoProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoProveedoresLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(paneCrudProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        paneModalProveedor.setBackground(new java.awt.Color(255, 255, 255));

        paneContenidoVentana.setOpaque(false);

        paneAtributosProveedor.setBackground(new java.awt.Color(204, 204, 204));
        paneAtributosProveedor.setOpaque(false);

        paneTelefono.setOpaque(false);

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefono.setText("Telefono");

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneTelefonoLayout = new javax.swing.GroupLayout(paneTelefono);
        paneTelefono.setLayout(paneTelefonoLayout);
        paneTelefonoLayout.setHorizontalGroup(
            paneTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneTelefonoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(paneTelefonoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTelefono)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTelefonoLayout.setVerticalGroup(
            paneTelefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTelefonoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        paneNombre.setOpaque(false);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        javax.swing.GroupLayout paneNombreLayout = new javax.swing.GroupLayout(paneNombre);
        paneNombre.setLayout(paneNombreLayout);
        paneNombreLayout.setHorizontalGroup(
            paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNombreLayout.createSequentialGroup()
                .addGroup(paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneNombreLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblNombre))
                    .addGroup(paneNombreLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneNombreLayout.setVerticalGroup(
            paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNombreLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDireccion.setOpaque(false);

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDireccion.setText("Direccion");

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDireccion.setToolTipText("");

        javax.swing.GroupLayout paneDireccionLayout = new javax.swing.GroupLayout(paneDireccion);
        paneDireccion.setLayout(paneDireccionLayout);
        paneDireccionLayout.setHorizontalGroup(
            paneDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDireccionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(paneDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        paneDireccionLayout.setVerticalGroup(
            paneDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDireccionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        paneRuc.setOpaque(false);

        txtRuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblRuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRuc.setText("RUC");

        javax.swing.GroupLayout paneRucLayout = new javax.swing.GroupLayout(paneRuc);
        paneRuc.setLayout(paneRucLayout);
        paneRucLayout.setHorizontalGroup(
            paneRucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRucLayout.createSequentialGroup()
                .addGroup(paneRucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneRucLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblRuc))
                    .addGroup(paneRucLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneRucLayout.setVerticalGroup(
            paneRucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRucLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblRuc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneAtributosProveedorLayout = new javax.swing.GroupLayout(paneAtributosProveedor);
        paneAtributosProveedor.setLayout(paneAtributosProveedorLayout);
        paneAtributosProveedorLayout.setHorizontalGroup(
            paneAtributosProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAtributosProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAtributosProveedorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(paneTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneAtributosProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(paneDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneAtributosProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paneNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        paneAtributosProveedorLayout.setVerticalGroup(
            paneAtributosProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAtributosProveedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );

        paneBotones.setOpaque(false);

        btnCancelar.setBackground(new java.awt.Color(102, 102, 255));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCancelarMouseMoved(evt);
            }
        });
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(102, 102, 255));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnGuardarMouseMoved(evt);
            }
        });
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoVentanaLayout = new javax.swing.GroupLayout(paneContenidoVentana);
        paneContenidoVentana.setLayout(paneContenidoVentanaLayout);
        paneContenidoVentanaLayout.setHorizontalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(paneAtributosProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneContenidoVentanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneContenidoVentanaLayout.setVerticalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneAtributosProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        paneHeader.setBackground(new java.awt.Color(25, 34, 143));

        lblHeaderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        paneHeaderOpciones.setBackground(new java.awt.Color(27, 39, 187));
        paneHeaderOpciones.setOpaque(false);

        lblCerrarVentana.setBackground(new java.awt.Color(255, 58, 97));
        lblCerrarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarVentana.png"))); // NOI18N
        lblCerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseMoved(evt);
            }
        });
        lblCerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneHeaderOpcionesLayout = new javax.swing.GroupLayout(paneHeaderOpciones);
        paneHeaderOpciones.setLayout(paneHeaderOpcionesLayout);
        paneHeaderOpcionesLayout.setHorizontalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderOpcionesLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(lblCerrarVentana)
                .addGap(48, 48, 48))
        );
        paneHeaderOpcionesLayout.setVerticalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderOpcionesLayout.createSequentialGroup()
                .addComponent(lblCerrarVentana)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Nuevo Proveedor");
        lbltitulo.setToolTipText("");

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHeaderLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHeaderLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                        .addComponent(lbltitulo)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout paneModalProveedorLayout = new javax.swing.GroupLayout(paneModalProveedor);
        paneModalProveedor.setLayout(paneModalProveedorLayout);
        paneModalProveedorLayout.setHorizontalGroup(
            paneModalProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
            .addGroup(paneModalProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneModalProveedorLayout.setVerticalGroup(
            paneModalProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModalProveedorLayout.createSequentialGroup()
                .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(paneModalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneContenidoProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(paneModalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        // TODO add your handling code here:
        Color Micolor= new Color(0,0,204);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        Color Micolor= new Color(72,84,247);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
        // TODO add your handling code here:
         btnEditar.setBackground(new Color(255,227,82)); 
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
         btnEditar.setBackground(new Color(255,214,0)); 
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseMoved
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(249,98,98));
    }//GEN-LAST:event_btnEliminarMouseMoved

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(228,77,77));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnNuevoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseMoved
        // TODO add your handling code here:
        btnNuevo.setBackground(new Color(0,222,29));
    }//GEN-LAST:event_btnNuevoMouseMoved

    private void btnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseExited
        // TODO add your handling code here:
        btnNuevo.setBackground(new Color(0,197,26)); 
    }//GEN-LAST:event_btnNuevoMouseExited

    private void btnCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseMoved
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(62,62,241));
    }//GEN-LAST:event_btnCancelarMouseMoved

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255));
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtRuc.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseMoved
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(62,62,241));
    }//GEN-LAST:event_btnGuardarMouseMoved

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        
        btnGuardar.setBackground(new Color(102,102,255));
       
        if(editNuevo){
            Guardar();
        }else{
            Editar(idSeleccionado);
        }
        
        txtRuc.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        iniTablaProveedores();
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void lblCerrarVentanaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseMoved
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(true);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseMoved

    private void lblCerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseClicked
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtRuc.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
    }//GEN-LAST:event_lblCerrarVentanaMouseClicked

    private void lblCerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseExited
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseExited

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        // TODO add your handling code here:
        editNuevo=true;
        NuevoModalProveedor();
        dialog.setLocationRelativeTo(null); // centra el dialogo en la pantalla
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        TableModel model = tblProveedores.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblProveedores.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            // Obtiene los valores de las columnas de la fila seleccionada
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna
            Object value2 = model.getValueAt(selectedRow, 1); // Valor de la primera columna
            Object value3 = model.getValueAt(selectedRow, 2); // Valor de la primera columna
            Object value4 = model.getValueAt(selectedRow, 3); // Valor de la primera columna
            Object value5 = model.getValueAt(selectedRow, 4); // Valor de la primera columna
            
            int idProveedor = Integer.parseInt(value1.toString());
            
            txtNombre.setText(value2.toString());
            txtRuc.setText(value3.toString());
            txtTelefono.setText(value4.toString());
            txtDireccion.setText(value5.toString());
            
            idSeleccionado=idProveedor;
            editNuevo=false;
            EditarModalProveedor();
            dialog.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialog.setVisible(true);
            
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        TableModel model = tblProveedores.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblProveedores.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna   
            int idProveedor = Integer.parseInt(value1.toString());
            
            Eliminar(idProveedor);
            
        }
        iniTablaProveedores();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
       iniTablaProveedores();
       String elementoBusqueda = txtBusqueda.getText(); // Elemento que se desea buscar
        if(!elementoBusqueda.equals("")){
            DefaultTableModel model = (DefaultTableModel) tblProveedores.getModel();
            int rowCount = model.getRowCount();
            int columnCount = model.getColumnCount();

            List<Integer> filasCoincidentes = new ArrayList<>();

            for (int row = 0; row < rowCount; row++) {
                for (int column = 0; column < columnCount; column++) {
                    Object cellValue = model.getValueAt(row, column);
                    String cellString = String.valueOf(cellValue);

                    if (cellString.equals(elementoBusqueda)) {
                        filasCoincidentes.add(row);
                        // Puedes realizar alguna acción adicional, como resaltar la fila
                    }
                }
            }
            DefaultTableModel modelProveedor = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            modelProveedor.addColumn("Id");
            modelProveedor.addColumn("Nombre");
            modelProveedor.addColumn("RUC");
            modelProveedor.addColumn("Telefono");
            modelProveedor.addColumn("Direccion");

            for (Integer filaCoincidente : filasCoincidentes) {
                Object[] rowData = new Object[5];
                rowData[0] = tblProveedores.getValueAt(filaCoincidente, 0);  
                rowData[1] = tblProveedores.getValueAt(filaCoincidente, 1);  
                rowData[2] = tblProveedores.getValueAt(filaCoincidente, 2);  
                rowData[3] = tblProveedores.getValueAt(filaCoincidente, 3);  
                rowData[4] = tblProveedores.getValueAt(filaCoincidente, 4);  
 
                modelProveedor.addRow(rowData);
            }
      
            tblProveedores.setModel(modelProveedor);
            tblProveedores.repaint();
        }else{
            iniTablaProveedores();
        }
        
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrarVentana;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblHeaderLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloIconArticulos;
    private javax.swing.JLabel lblTituloIconArticulos1;
    private javax.swing.JLabel lblTituloIconArticulos2;
    private javax.swing.JLabel lblTituloIconArticulos3;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel paneAtributosProveedor;
    private javax.swing.JPanel paneBotones;
    private javax.swing.JPanel paneBuscar;
    private javax.swing.JPanel paneContenedor;
    private javax.swing.JPanel paneContenidoProveedores;
    private javax.swing.JPanel paneContenidoVentana;
    private javax.swing.JPanel paneCrudProveedores;
    private javax.swing.JPanel paneDireccion;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JPanel paneHeaderOpciones;
    private javax.swing.JPanel paneModalProveedor;
    private javax.swing.JPanel paneNombre;
    private javax.swing.JPanel paneOpcionesProveedores;
    private javax.swing.JPanel paneRuc;
    private javax.swing.JPanel paneTablaProveedores;
    private javax.swing.JPanel paneTelefono;
    private javax.swing.JPanel paneTituloProveedores;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void iniComplementLayout() {
        getContentPane().setLayout(new CardLayout());
        
        getContentPane().add(paneContenidoProveedores);
        getContentPane().remove(paneModalProveedor);
        //layaout para el contenido
        FlowLayout flowlayoutContenido = new FlowLayout(FlowLayout.CENTER,10,70);
        paneContenidoProveedores.setLayout(flowlayoutContenido);
            FlowLayout flowlayoutTituloArticulos = new FlowLayout(FlowLayout.LEFT,10,10);
            paneCrudProveedores.setLayout(new BorderLayout());
                paneTituloProveedores.setLayout(flowlayoutTituloArticulos);
                paneCrudProveedores.add(paneTituloProveedores, java.awt.BorderLayout.PAGE_START);
                paneCrudProveedores.add(paneContenedor, java.awt.BorderLayout.CENTER);
                    paneContenedor.setLayout(new BorderLayout());
                    paneContenedor.add(paneOpcionesProveedores, java.awt.BorderLayout.PAGE_START);
                    paneContenedor.add(paneTablaProveedores, java.awt.BorderLayout.CENTER);
                    
                FlowLayout flowlayoutOpArticulos= new FlowLayout(FlowLayout.RIGHT,15,30);
                paneOpcionesProveedores.setLayout(flowlayoutOpArticulos);
                    FlowLayout flowlayoutBoton = new FlowLayout(FlowLayout.CENTER,10,8);
                    paneBuscar.setLayout(new BoxLayout(paneBuscar, BoxLayout.X_AXIS));
                    btnNuevo.setLayout(flowlayoutBoton);
                    btnEditar.setLayout(flowlayoutBoton);
                    btnEliminar.setLayout(flowlayoutBoton);
        
        //modal nuevo
        //layout de la ventana  
         paneModalProveedor.setLayout(new BorderLayout());

         paneModalProveedor.add(paneContenidoVentana, java.awt.BorderLayout.CENTER);
         paneModalProveedor.add(paneHeader, java.awt.BorderLayout.PAGE_START);

          //layout de header de la ventana
         paneHeader.setLayout(new BoxLayout(paneHeader, BoxLayout.X_AXIS));

         FlowLayout flowlayoutHeaderOpciones = new FlowLayout(FlowLayout.RIGHT,0,0);
         paneHeaderOpciones.setLayout(flowlayoutHeaderOpciones);
         paneHeader.add(lblHeaderLogo);
         paneHeader.add(lbltitulo);
         paneHeader.add(Box.createHorizontalGlue()); // Espaciador flexible
         paneHeader.add(paneHeaderOpciones);
         //contenido del modal
         
         //contenerdo de los atributos
         paneContenidoVentana.setLayout(new BorderLayout());
         paneContenidoVentana.add(paneAtributosProveedor, java.awt.BorderLayout.CENTER);
         paneContenidoVentana.add(paneBotones, java.awt.BorderLayout.PAGE_END);
         FlowLayout flowlayoutAtributosUsuario = new FlowLayout(FlowLayout.CENTER,10,30);
         paneAtributosProveedor.setLayout(flowlayoutAtributosUsuario);
            //contenedor de los txt y label
            paneRuc.setLayout(new BoxLayout(paneRuc, BoxLayout.Y_AXIS));
                txtRuc.setAlignmentX(LEFT_ALIGNMENT);
                lblRuc.setAlignmentX(LEFT_ALIGNMENT);
                paneRuc.add(lblRuc);     
                paneRuc.add(txtRuc); 
            paneNombre.setLayout(new BoxLayout(paneNombre, BoxLayout.Y_AXIS));
                txtNombre.setAlignmentX(LEFT_ALIGNMENT);
                lblNombre.setAlignmentX(LEFT_ALIGNMENT);
                paneNombre.add(lblNombre);     
                paneNombre.add(txtNombre); 
            paneTelefono.setLayout(new BoxLayout(paneTelefono, BoxLayout.Y_AXIS));
                txtTelefono.setAlignmentX(LEFT_ALIGNMENT);
                lblTelefono.setAlignmentX(LEFT_ALIGNMENT);
                paneTelefono.add(lblTelefono);     
                paneTelefono.add(txtTelefono); 
            paneDireccion.setLayout(new BoxLayout(paneDireccion, BoxLayout.Y_AXIS));
                txtDireccion.setAlignmentX(LEFT_ALIGNMENT);
                lblDireccion.setAlignmentX(LEFT_ALIGNMENT);
                paneDireccion.add(lblDireccion);     
                paneDireccion.add(txtDireccion); 
                
        
        paneAtributosProveedor.add(paneNombre);
        paneAtributosProveedor.add(paneRuc); 
        paneAtributosProveedor.add(paneTelefono);
        paneAtributosProveedor.add(paneDireccion);
        
        
        FlowLayout flowlayoutBotones = new FlowLayout(FlowLayout.CENTER,30,10);
        paneBotones.setLayout(flowlayoutBotones);
        btnGuardar.setLayout(new GridBagLayout());
        btnCancelar.setLayout(new GridBagLayout());
        
    }

    private void iniSize() {
         //tamaño de ventana
        this.setBounds(0,0,1400, 900);
        
        //tamaño del panel de contenido
        paneContenidoProveedores.setPreferredSize(new Dimension( 1, 1));    
            paneCrudProveedores.setPreferredSize(new Dimension( 1000, 650));    
                paneOpcionesProveedores.setPreferredSize(new Dimension( 1000, 100));  
                //paneTablaArticulos.setPreferredSize(new Dimension( 1000, 100));  
                    txtBusqueda.setPreferredSize(new Dimension( 200, 40));
                    btnBuscar.setPreferredSize(new Dimension( 60, 40));
                    btnNuevo.setPreferredSize(new Dimension( 200, 40));
                    btnEditar.setPreferredSize(new Dimension( 200, 40));
                    btnEliminar.setPreferredSize(new Dimension( 200, 40));
        //modal
            //tamaño del panel header
            paneHeader.setPreferredSize(new Dimension( 1, 40));
            lblHeaderLogo.setSize(new Dimension( 40, 40));
            lblCerrarVentana.setPreferredSize(new Dimension( 40, 40));
            
            //tamaño del contenido
            paneAtributosProveedor.setPreferredSize(new Dimension(380,60));
            paneRuc.setPreferredSize(new Dimension(380,60));
            paneNombre.setPreferredSize(new Dimension(380,60));
            paneTelefono.setPreferredSize(new Dimension(380,60));
            paneDireccion.setPreferredSize(new Dimension(380,60));
            
            paneBotones.setPreferredSize(new Dimension(450,80));
            btnGuardar.setPreferredSize(new Dimension(150,40));
            btnCancelar.setPreferredSize(new Dimension(150,40));            
    }           


    private void iniDiseños() {
      //modal
            //inicaiar imagenes del Header de la ventana.
            redimencionarImagenen(lblHeaderLogo,"/img/logo.png");       
            lblCerrarVentana.setVerticalAlignment(SwingConstants.CENTER);
            lblCerrarVentana.setHorizontalAlignment(SwingConstants.CENTER);
    }
    public JPanel obtenerPanel(){
        return this.paneContenidoProveedores;
    }
    public void redimencionarImagenen(JLabel lblicon,String img){
      // Cargamos la imagen desde un archivo
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource(img));//"/Img/login2.jpg"

        // Ajustamos el tamaño de la imagen al tamaño del JLabel
        Image image = icon.getImage();
        Image scaledImage = image.getScaledInstance(lblicon.getWidth(), lblicon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Establecemos la imagen en el JLabel                
            
        ///labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.jpg"))); 
        lblicon.setIcon(scaledIcon);    
    }
    private void NuevoModalProveedor(){
        lbltitulo.setText("Nuevo Proveedor");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalProveedor); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,550)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    private void EditarModalProveedor(){
        
        lbltitulo.setText("Modificar Proveedor");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalProveedor); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,550)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    private void iniTablaProveedores(){
        tabla = proveedoresController.ObtenerProveedores();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("RUC");
        model.addColumn("Telefono");
        model.addColumn("Direccion");
        
        for(Map<String, Object> res : tabla){
            model.addRow(new Object[]{res.get("id"), res.get("nombre"),res.get("ruc"),res.get("telefono"),res.get("direccion")});        
        }
        
        tblProveedores.setModel(model);
        tblProveedores.repaint();
    }

    private void Guardar(){
        
        String nombre=txtNombre.getText();
        String ruc=txtRuc.getText();
        String telefono=txtTelefono.getText();
        String direccion=txtDireccion.getText();
   
        if(proveedoresController.registrarProveedor(nombre, ruc, telefono, direccion)){
            ModalNotificar modal = new ModalNotificar("Guardado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
    }
    private void Editar(int id){

        String nombre=txtNombre.getText();
        String ruc=txtRuc.getText();
        String telefono=txtTelefono.getText();
        String direccion=txtDireccion.getText();
        
        if(proveedoresController.actualizarProveedor(id,nombre, ruc, telefono, direccion)){
            ModalNotificar modal = new ModalNotificar("Actualizado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
        
    }
    private void Eliminar(int id){

        if(proveedoresController.EliminarProveedor(id)){
            ModalNotificar modal = new ModalNotificar("Eliminado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
        
    }
}
