/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.EscritorioController;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import org.jfree.chart.ChartPanel;
import util.Graficos;

/**
 *
 * @author enriq
 */
public class panelEscritorio extends javax.swing.JFrame {

    /**
     * Creates new form panelEscritorio
     */
    EscritorioController escritorioController = new EscritorioController();
    Map<String, Object> response = new HashMap<>();
    
    Graficos graficos = new Graficos();
    ChartPanel graficoPastel = graficos.graficoPastel();
    ChartPanel graficoBarrasApiladas = graficos.graficoBarrasApiladas();
    ChartPanel graficoLineas=graficos.graficoLineas();
    
    public panelEscritorio() {
        initComponents();
        iniComplementLayout();
        iniSize();
        iniDiseños();
        iniDatosEscritorio();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneContenidoEscritorio = new javax.swing.JPanel();
        paneMostrarComprasUsuario = new javax.swing.JPanel();
        paneTituloMostrarComprasUsuario = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblMostrarComprasUsuario = new javax.swing.JLabel();
        paneMostrarProveedores = new javax.swing.JPanel();
        paneTituloMostrarProveedores = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lblMostrarProveedores = new javax.swing.JLabel();
        paneMostrarArticulos = new javax.swing.JPanel();
        paneTituloMostrarArticulos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblMostrarArticulos = new javax.swing.JLabel();
        paneMostrarIngresos = new javax.swing.JPanel();
        paneTituloMostrarIngresos = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblMostrarIngresos = new javax.swing.JLabel();
        paneMostrarVentasUsuario = new javax.swing.JPanel();
        paneTituloMostrarVentasUsuario = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblMostrarVentasUsuario = new javax.swing.JLabel();
        paneMostrarCategorias = new javax.swing.JPanel();
        paneTituloMostrarCategorias = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMostrarCategorias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneContenidoEscritorio.setBackground(new java.awt.Color(229, 238, 255));

        paneMostrarComprasUsuario.setBackground(new java.awt.Color(253, 170, 32));

        paneTituloMostrarComprasUsuario.setBackground(new java.awt.Color(211, 134, 38));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Compras Usuario");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloMostrarComprasUsuarioLayout = new javax.swing.GroupLayout(paneTituloMostrarComprasUsuario);
        paneTituloMostrarComprasUsuario.setLayout(paneTituloMostrarComprasUsuarioLayout);
        paneTituloMostrarComprasUsuarioLayout.setHorizontalGroup(
            paneTituloMostrarComprasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarComprasUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        paneTituloMostrarComprasUsuarioLayout.setVerticalGroup(
            paneTituloMostrarComprasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarComprasUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloMostrarComprasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblMostrarComprasUsuario.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblMostrarComprasUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrarComprasUsuario.setText("1000");
        lblMostrarComprasUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneMostrarComprasUsuarioLayout = new javax.swing.GroupLayout(paneMostrarComprasUsuario);
        paneMostrarComprasUsuario.setLayout(paneMostrarComprasUsuarioLayout);
        paneMostrarComprasUsuarioLayout.setHorizontalGroup(
            paneMostrarComprasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloMostrarComprasUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMostrarComprasUsuarioLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblMostrarComprasUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneMostrarComprasUsuarioLayout.setVerticalGroup(
            paneMostrarComprasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMostrarComprasUsuarioLayout.createSequentialGroup()
                .addComponent(paneTituloMostrarComprasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMostrarComprasUsuario)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        paneMostrarProveedores.setBackground(new java.awt.Color(255, 255, 255));

        paneTituloMostrarProveedores.setBackground(new java.awt.Color(31, 54, 193));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Proveedores");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedores.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloMostrarProveedoresLayout = new javax.swing.GroupLayout(paneTituloMostrarProveedores);
        paneTituloMostrarProveedores.setLayout(paneTituloMostrarProveedoresLayout);
        paneTituloMostrarProveedoresLayout.setHorizontalGroup(
            paneTituloMostrarProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloMostrarProveedoresLayout.setVerticalGroup(
            paneTituloMostrarProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloMostrarProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblMostrarProveedores.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblMostrarProveedores.setText("1000");
        lblMostrarProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneMostrarProveedoresLayout = new javax.swing.GroupLayout(paneMostrarProveedores);
        paneMostrarProveedores.setLayout(paneMostrarProveedoresLayout);
        paneMostrarProveedoresLayout.setHorizontalGroup(
            paneMostrarProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloMostrarProveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMostrarProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMostrarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneMostrarProveedoresLayout.setVerticalGroup(
            paneMostrarProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMostrarProveedoresLayout.createSequentialGroup()
                .addComponent(paneTituloMostrarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMostrarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        paneMostrarArticulos.setBackground(new java.awt.Color(255, 255, 255));

        paneTituloMostrarArticulos.setBackground(new java.awt.Color(31, 54, 193));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Articulos");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/articulo.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloMostrarArticulosLayout = new javax.swing.GroupLayout(paneTituloMostrarArticulos);
        paneTituloMostrarArticulos.setLayout(paneTituloMostrarArticulosLayout);
        paneTituloMostrarArticulosLayout.setHorizontalGroup(
            paneTituloMostrarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarArticulosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloMostrarArticulosLayout.setVerticalGroup(
            paneTituloMostrarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarArticulosLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(paneTituloMostrarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel30))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lblMostrarArticulos.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblMostrarArticulos.setText("1000");
        lblMostrarArticulos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneMostrarArticulosLayout = new javax.swing.GroupLayout(paneMostrarArticulos);
        paneMostrarArticulos.setLayout(paneMostrarArticulosLayout);
        paneMostrarArticulosLayout.setHorizontalGroup(
            paneMostrarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloMostrarArticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMostrarArticulosLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblMostrarArticulos)
                .addGap(60, 60, 60))
        );
        paneMostrarArticulosLayout.setVerticalGroup(
            paneMostrarArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMostrarArticulosLayout.createSequentialGroup()
                .addComponent(paneTituloMostrarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMostrarArticulos)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        paneMostrarIngresos.setBackground(new java.awt.Color(255, 255, 255));

        paneTituloMostrarIngresos.setBackground(new java.awt.Color(31, 54, 193));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Ingresos ");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signoDolar.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloMostrarIngresosLayout = new javax.swing.GroupLayout(paneTituloMostrarIngresos);
        paneTituloMostrarIngresos.setLayout(paneTituloMostrarIngresosLayout);
        paneTituloMostrarIngresosLayout.setHorizontalGroup(
            paneTituloMostrarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarIngresosLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloMostrarIngresosLayout.setVerticalGroup(
            paneTituloMostrarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarIngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloMostrarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel31))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblMostrarIngresos.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblMostrarIngresos.setText("1000000.00");
        lblMostrarIngresos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneMostrarIngresosLayout = new javax.swing.GroupLayout(paneMostrarIngresos);
        paneMostrarIngresos.setLayout(paneMostrarIngresosLayout);
        paneMostrarIngresosLayout.setHorizontalGroup(
            paneMostrarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloMostrarIngresos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMostrarIngresosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblMostrarIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        paneMostrarIngresosLayout.setVerticalGroup(
            paneMostrarIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMostrarIngresosLayout.createSequentialGroup()
                .addComponent(paneTituloMostrarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMostrarIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        paneMostrarVentasUsuario.setBackground(new java.awt.Color(255, 255, 255));

        paneTituloMostrarVentasUsuario.setBackground(new java.awt.Color(31, 54, 193));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ventas Usuario");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloMostrarVentasUsuarioLayout = new javax.swing.GroupLayout(paneTituloMostrarVentasUsuario);
        paneTituloMostrarVentasUsuario.setLayout(paneTituloMostrarVentasUsuarioLayout);
        paneTituloMostrarVentasUsuarioLayout.setHorizontalGroup(
            paneTituloMostrarVentasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarVentasUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(42, 42, 42))
        );
        paneTituloMostrarVentasUsuarioLayout.setVerticalGroup(
            paneTituloMostrarVentasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarVentasUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloMostrarVentasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel12))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblMostrarVentasUsuario.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblMostrarVentasUsuario.setText("1000");
        lblMostrarVentasUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneMostrarVentasUsuarioLayout = new javax.swing.GroupLayout(paneMostrarVentasUsuario);
        paneMostrarVentasUsuario.setLayout(paneMostrarVentasUsuarioLayout);
        paneMostrarVentasUsuarioLayout.setHorizontalGroup(
            paneMostrarVentasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloMostrarVentasUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMostrarVentasUsuarioLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblMostrarVentasUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneMostrarVentasUsuarioLayout.setVerticalGroup(
            paneMostrarVentasUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMostrarVentasUsuarioLayout.createSequentialGroup()
                .addComponent(paneTituloMostrarVentasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMostrarVentasUsuario)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        paneMostrarCategorias.setBackground(new java.awt.Color(181, 58, 248));

        paneTituloMostrarCategorias.setBackground(new java.awt.Color(134, 49, 162));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Categorias");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloMostrarCategoriasLayout = new javax.swing.GroupLayout(paneTituloMostrarCategorias);
        paneTituloMostrarCategorias.setLayout(paneTituloMostrarCategoriasLayout);
        paneTituloMostrarCategoriasLayout.setHorizontalGroup(
            paneTituloMostrarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarCategoriasLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(70, 70, 70))
        );
        paneTituloMostrarCategoriasLayout.setVerticalGroup(
            paneTituloMostrarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloMostrarCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloMostrarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblMostrarCategorias.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMostrarCategorias.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrarCategorias.setText("1000");
        lblMostrarCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneMostrarCategoriasLayout = new javax.swing.GroupLayout(paneMostrarCategorias);
        paneMostrarCategorias.setLayout(paneMostrarCategoriasLayout);
        paneMostrarCategoriasLayout.setHorizontalGroup(
            paneMostrarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloMostrarCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMostrarCategoriasLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblMostrarCategorias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneMostrarCategoriasLayout.setVerticalGroup(
            paneMostrarCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMostrarCategoriasLayout.createSequentialGroup()
                .addComponent(paneTituloMostrarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMostrarCategorias)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoEscritorioLayout = new javax.swing.GroupLayout(paneContenidoEscritorio);
        paneContenidoEscritorio.setLayout(paneContenidoEscritorioLayout);
        paneContenidoEscritorioLayout.setHorizontalGroup(
            paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoEscritorioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneMostrarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneMostrarVentasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneMostrarComprasUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneMostrarProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneContenidoEscritorioLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(paneMostrarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneContenidoEscritorioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(paneMostrarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        paneContenidoEscritorioLayout.setVerticalGroup(
            paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoEscritorioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneMostrarVentasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneMostrarComprasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneMostrarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneContenidoEscritorioLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(paneContenidoEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneMostrarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneMostrarProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneContenidoEscritorioLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(paneMostrarIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneContenidoEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelEscritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelEscritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel lblMostrarArticulos;
    private javax.swing.JLabel lblMostrarCategorias;
    private javax.swing.JLabel lblMostrarComprasUsuario;
    private javax.swing.JLabel lblMostrarIngresos;
    private javax.swing.JLabel lblMostrarProveedores;
    private javax.swing.JLabel lblMostrarVentasUsuario;
    private javax.swing.JPanel paneContenidoEscritorio;
    private javax.swing.JPanel paneMostrarArticulos;
    private javax.swing.JPanel paneMostrarCategorias;
    private javax.swing.JPanel paneMostrarComprasUsuario;
    private javax.swing.JPanel paneMostrarIngresos;
    private javax.swing.JPanel paneMostrarProveedores;
    private javax.swing.JPanel paneMostrarVentasUsuario;
    private javax.swing.JPanel paneTituloMostrarArticulos;
    private javax.swing.JPanel paneTituloMostrarCategorias;
    private javax.swing.JPanel paneTituloMostrarComprasUsuario;
    private javax.swing.JPanel paneTituloMostrarIngresos;
    private javax.swing.JPanel paneTituloMostrarProveedores;
    private javax.swing.JPanel paneTituloMostrarVentasUsuario;
    // End of variables declaration//GEN-END:variables

    private void iniComplementLayout() {
        getContentPane().setLayout(new CardLayout());
        
        getContentPane().add(paneContenidoEscritorio);
        //layaout para el contenido
        //FlowLayout flowlayoutContenido = new FlowLayout(FlowLayout.CENTER,60,60);
        paneContenidoEscritorio.setLayout(new GridBagLayout());
            FlowLayout flowlayoutTituloMostrar = new FlowLayout(FlowLayout.LEFT,10,5);
            paneMostrarVentasUsuario.setLayout(new BorderLayout());
                paneTituloMostrarVentasUsuario.setLayout(flowlayoutTituloMostrar);
                paneMostrarVentasUsuario.add(paneTituloMostrarVentasUsuario, java.awt.BorderLayout.PAGE_START);
                paneMostrarVentasUsuario.add(lblMostrarVentasUsuario, java.awt.BorderLayout.CENTER);
                
            paneMostrarComprasUsuario.setLayout(new BorderLayout());
                paneTituloMostrarComprasUsuario.setLayout(flowlayoutTituloMostrar);
                paneMostrarComprasUsuario.add(paneTituloMostrarComprasUsuario, java.awt.BorderLayout.PAGE_START);
                paneMostrarComprasUsuario.add(lblMostrarComprasUsuario, java.awt.BorderLayout.CENTER);
                
            paneMostrarArticulos.setLayout(new BorderLayout());
                paneTituloMostrarArticulos.setLayout(flowlayoutTituloMostrar);
                paneMostrarArticulos.add(paneTituloMostrarArticulos, java.awt.BorderLayout.PAGE_START);
                paneMostrarArticulos.add(lblMostrarArticulos, java.awt.BorderLayout.CENTER);
                
            paneMostrarCategorias.setLayout(new BorderLayout());
                paneTituloMostrarCategorias.setLayout(flowlayoutTituloMostrar);
                paneMostrarCategorias.add(paneTituloMostrarCategorias, java.awt.BorderLayout.PAGE_START);
                paneMostrarCategorias.add(lblMostrarCategorias, java.awt.BorderLayout.CENTER);
                
            paneMostrarProveedores.setLayout(new BorderLayout());
                paneTituloMostrarProveedores.setLayout(flowlayoutTituloMostrar);
                paneMostrarProveedores.add(paneTituloMostrarProveedores, java.awt.BorderLayout.PAGE_START);
                paneMostrarProveedores.add(lblMostrarProveedores, java.awt.BorderLayout.CENTER);
                
            paneMostrarIngresos.setLayout(new BorderLayout());
                paneTituloMostrarIngresos.setLayout(flowlayoutTituloMostrar);
                paneMostrarIngresos.add(paneTituloMostrarIngresos, java.awt.BorderLayout.PAGE_START);
                paneMostrarIngresos.add(lblMostrarIngresos, java.awt.BorderLayout.CENTER);
                
        //paneContenidoEscritorio.add(paneMostrarVentasUsuario);
        paneContenidoEscritorio.remove(paneMostrarComprasUsuario);
        //paneContenidoEscritorio.add(paneMostrarArticulos);
        paneContenidoEscritorio.remove(paneMostrarCategorias);
        //paneContenidoEscritorio.add(paneMostrarProveedores);
        //paneContenidoEscritorio.add(paneMostrarIngresos);

        GridBagConstraints constraints = new GridBagConstraints();
        

        // Configurar los márgenes (separación)
        constraints.insets = new Insets(20, 20, 0, 0); 

        // Agregar componentes
        constraints.fill = GridBagConstraints.BOTH;
        constraints.weightx = 0.0; // No se expande horizontalmente
        constraints.weighty = 1.0; // No se expande verticalmente
        
        constraints.gridx = 0; // Columna 0
        constraints.gridy = 0; // Fila 0
        paneContenidoEscritorio.add(paneMostrarVentasUsuario, constraints);
        constraints.insets = new Insets(10, 20, 0, 0);
        constraints.gridx = 0; // Columna 0
        constraints.gridy = 1; // Fila 1
        paneContenidoEscritorio.add(paneMostrarArticulos, constraints);
        constraints.insets = new Insets(10, 20, 0, 0);
        constraints.gridx = 0; // Columna 0
        constraints.gridy = 2; // Fila 2
        paneContenidoEscritorio.add(paneMostrarProveedores, constraints);
        constraints.insets = new Insets(10, 20, 20, 0);
        constraints.gridx = 0; // Columna 0
        constraints.gridy = 3; // Fila 3
        paneContenidoEscritorio.add(paneMostrarIngresos, constraints);
        
        constraints.insets = new Insets(20, 10, 0, 20); 
        constraints.fill = GridBagConstraints.BOTH; 
        constraints.weightx = 1.0; 
        constraints.weighty = 1.0; 
        
        constraints.gridx = 1; // Columna 1
        constraints.gridy = 0; // Fila 0
        constraints.gridheight = 2; // Ocupar 2 filas
        constraints.gridwidth = 4; // Ocupar 1 columna
        paneContenidoEscritorio.add(graficoBarrasApiladas, constraints);
        constraints.insets = new Insets(10, 10, 20, 0);
        constraints.gridx = 1; // Columna 2
        constraints.gridy = 2; // Fila 0
        constraints.gridheight = 2; // Ocupar 4 filas
        constraints.gridwidth = 2; // Ocupar 1 columna
        paneContenidoEscritorio.add(graficoPastel, constraints);
        constraints.insets = new Insets(10, 10, 20, 20);
        constraints.gridx = 3; // Columna 3
        constraints.gridy = 2; // Fila 0
        constraints.gridheight = 2; // Ocupar 4 filas
        constraints.gridwidth = 2; // Ocupar 1 columna
        paneContenidoEscritorio.add(graficoLineas, constraints);
        
    }

    private void iniSize() {
         //tamaño de ventana
        this.setBounds(0,0,1400, 900);
         //tamaño del panel de contenido
        paneContenidoEscritorio.setPreferredSize(new Dimension( 1, 1));    
            paneMostrarVentasUsuario.setPreferredSize(new Dimension( 250, 150));
            paneMostrarComprasUsuario.setPreferredSize(new Dimension( 250, 150));
            paneMostrarArticulos.setPreferredSize(new Dimension( 250, 150));
            paneMostrarCategorias.setPreferredSize(new Dimension( 250, 150));
            paneMostrarProveedores.setPreferredSize(new Dimension( 250, 150));
            paneMostrarIngresos.setPreferredSize(new Dimension( 250, 150));
    }

    private void iniDiseños() {
        //centrar contenido de los panel que muestran la informacion
        lblMostrarVentasUsuario.setHorizontalAlignment(SwingConstants.CENTER);
        lblMostrarComprasUsuario.setHorizontalAlignment(SwingConstants.CENTER);
        lblMostrarArticulos.setHorizontalAlignment(SwingConstants.CENTER);
        lblMostrarCategorias.setHorizontalAlignment(SwingConstants.CENTER);
        lblMostrarProveedores.setHorizontalAlignment(SwingConstants.CENTER);
        lblMostrarIngresos.setHorizontalAlignment(SwingConstants.CENTER);
        
    }
    public JPanel obtenerPanel(){
        return this.paneContenidoEscritorio;
    }
    private void iniDatosEscritorio(){
        Integer cantVentas=(Integer)LoginFrame.sesionUsuario.get("cantVenta");
        lblMostrarVentasUsuario.setText(cantVentas.toString());
        
        response=escritorioController.TotalProveedores();
        lblMostrarProveedores.setText(response.get("Cantidad").toString());
        
        response=escritorioController.TotalIngresos();
        lblMostrarIngresos.setText(response.get("Total").toString());
        
        response=escritorioController.TotalArticulos();
        lblMostrarArticulos.setText(response.get("Cantidad").toString());
    }
}
