/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.ArticulosController;
import Controller.CompraController;
import Controller.ReportesController;
import Controller.VentaController;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import util.ExcelUtil;

/**
 *
 * @author enriq
 */
public class panelReportes extends javax.swing.JFrame {

    /**
     * Creates new form panelArticulos
     */
    CompraController compraController=new CompraController();
    ArticulosController articulosController=new ArticulosController();
    ReportesController reportesController=new ReportesController();
    VentaController ventaController=new VentaController();
    Map<String, Object>[] tabla;
    String campoTabla="Compras";
    ExcelUtil excelUtil = new ExcelUtil();
    public panelReportes() {
        initComponents();
        iniComplementLayout();
        iniSize();
        iniLocation();
        iniDiseños();
        iniTablaCompras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneContenidoReporte = new javax.swing.JPanel();
        paneCrudReporte = new javax.swing.JPanel();
        paneTituloReporte = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblTituloIconArticulos = new javax.swing.JLabel();
        paneContenedor = new javax.swing.JPanel();
        paneOpcionesReporte = new javax.swing.JPanel();
        paneFechaFin = new javax.swing.JPanel();
        lblFechaFin = new javax.swing.JLabel();
        dateFechaFin = new com.toedter.calendar.JDateChooser();
        paneFechaInicio = new javax.swing.JPanel();
        lblFechaInicio = new javax.swing.JLabel();
        dateFechaInicio = new com.toedter.calendar.JDateChooser();
        paneCampos = new javax.swing.JPanel();
        cbxCampos = new javax.swing.JComboBox<>();
        lblCampos = new javax.swing.JLabel();
        paneBotones = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        btnReporte = new javax.swing.JPanel();
        lblReporte = new javax.swing.JLabel();
        paneTablaReporte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        paneContenidoReporte.setBackground(new java.awt.Color(229, 238, 255));

        paneCrudReporte.setBackground(new java.awt.Color(255, 255, 255));
        paneCrudReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 4));

        paneTituloReporte.setBackground(new java.awt.Color(72, 84, 247));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reportes");

        lblTituloIconArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portapapeles.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloReporteLayout = new javax.swing.GroupLayout(paneTituloReporte);
        paneTituloReporte.setLayout(paneTituloReporteLayout);
        paneTituloReporteLayout.setHorizontalGroup(
            paneTituloReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloReporteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTituloIconArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloReporteLayout.setVerticalGroup(
            paneTituloReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneContenedor.setBackground(new java.awt.Color(153, 153, 153));

        paneOpcionesReporte.setBackground(new java.awt.Color(255, 255, 255));

        paneFechaFin.setOpaque(false);

        lblFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaFin.setText("Fecha Fin");

        dateFechaFin.setDateFormatString("yyyy-MM-dd");
        dateFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneFechaFinLayout = new javax.swing.GroupLayout(paneFechaFin);
        paneFechaFin.setLayout(paneFechaFinLayout);
        paneFechaFinLayout.setHorizontalGroup(
            paneFechaFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFechaFinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneFechaFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFin)
                    .addComponent(dateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        paneFechaFinLayout.setVerticalGroup(
            paneFechaFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFechaFinLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lblFechaFin)
                .addGap(18, 18, 18)
                .addComponent(dateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        java.util.Date fechaActual2 = new java.util.Date();

        dateFechaFin.setMaxSelectableDate(fechaActual2);

        dateFechaFin.getComponent(1).setEnabled(false);

        paneFechaInicio.setOpaque(false);

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFechaInicio.setText("Fecha inicio");

        dateFechaInicio.setDateFormatString("yyyy-MM-dd");
        dateFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneFechaInicioLayout = new javax.swing.GroupLayout(paneFechaInicio);
        paneFechaInicio.setLayout(paneFechaInicioLayout);
        paneFechaInicioLayout.setHorizontalGroup(
            paneFechaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneFechaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneFechaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio)
                    .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        paneFechaInicioLayout.setVerticalGroup(
            paneFechaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneFechaInicioLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lblFechaInicio)
                .addGap(18, 18, 18)
                .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        java.util.Date fechaActual1 = new java.util.Date();

        dateFechaInicio.setMaxSelectableDate(fechaActual1);

        dateFechaInicio.getComponent(1).setEnabled(false);

        paneCampos.setOpaque(false);

        cbxCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCampos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compras", "Ventas", "Inventario" }));
        cbxCampos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCamposItemStateChanged(evt);
            }
        });

        lblCampos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCampos.setText("Campos");

        javax.swing.GroupLayout paneCamposLayout = new javax.swing.GroupLayout(paneCampos);
        paneCampos.setLayout(paneCamposLayout);
        paneCamposLayout.setHorizontalGroup(
            paneCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCamposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbxCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(paneCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCampos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneCamposLayout.setVerticalGroup(
            paneCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCamposLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        paneBotones.setOpaque(false);

        btnBuscar.setBackground(new java.awt.Color(53, 58, 196));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        lblBuscar.setText("Buscar");
        lblBuscar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBuscar)
                .addContainerGap())
        );

        btnReporte.setBackground(new java.awt.Color(253, 124, 0));
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setToolTipText("");
        btnReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporte.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReporteMouseMoved(evt);
            }
        });
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteMouseExited(evt);
            }
        });

        lblReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReporte.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporteB.png"))); // NOI18N
        lblReporte.setText("Crear Reporte");

        javax.swing.GroupLayout btnReporteLayout = new javax.swing.GroupLayout(btnReporte);
        btnReporte.setLayout(btnReporteLayout);
        btnReporteLayout.setHorizontalGroup(
            btnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReporteLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblReporte)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        btnReporteLayout.setVerticalGroup(
            btnReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnReporteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReporte)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBotonesLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout paneOpcionesReporteLayout = new javax.swing.GroupLayout(paneOpcionesReporte);
        paneOpcionesReporte.setLayout(paneOpcionesReporteLayout);
        paneOpcionesReporteLayout.setHorizontalGroup(
            paneOpcionesReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOpcionesReporteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        paneOpcionesReporteLayout.setVerticalGroup(
            paneOpcionesReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOpcionesReporteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(paneOpcionesReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneOpcionesReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paneCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneFechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneOpcionesReporteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        paneTablaReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        tblReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReporte);

        javax.swing.GroupLayout paneTablaReporteLayout = new javax.swing.GroupLayout(paneTablaReporte);
        paneTablaReporte.setLayout(paneTablaReporteLayout);
        paneTablaReporteLayout.setHorizontalGroup(
            paneTablaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        paneTablaReporteLayout.setVerticalGroup(
            paneTablaReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneContenedorLayout = new javax.swing.GroupLayout(paneContenedor);
        paneContenedor.setLayout(paneContenedorLayout);
        paneContenedorLayout.setHorizontalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneTablaReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneOpcionesReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneContenedorLayout.setVerticalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneOpcionesReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneTablaReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneCrudReporteLayout = new javax.swing.GroupLayout(paneCrudReporte);
        paneCrudReporte.setLayout(paneCrudReporteLayout);
        paneCrudReporteLayout.setHorizontalGroup(
            paneCrudReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneCrudReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneCrudReporteLayout.setVerticalGroup(
            paneCrudReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCrudReporteLayout.createSequentialGroup()
                .addComponent(paneTituloReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoReporteLayout = new javax.swing.GroupLayout(paneContenidoReporte);
        paneContenidoReporte.setLayout(paneContenidoReporteLayout);
        paneContenidoReporteLayout.setHorizontalGroup(
            paneContenidoReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoReporteLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(paneCrudReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        paneContenidoReporteLayout.setVerticalGroup(
            paneContenidoReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoReporteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(paneCrudReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(paneContenidoReporte);
        paneContenidoReporte.setBounds(0, 0, 1070, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseMoved
        // TODO add your handling code here:
        btnReporte.setBackground(new Color(255,167,57));
    }//GEN-LAST:event_btnReporteMouseMoved

    private void btnReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseExited
        // TODO add your handling code here:
        btnReporte.setBackground(new Color(253,124,0));
    }//GEN-LAST:event_btnReporteMouseExited

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        // TODO add your handling code here:
        btnBuscar.setBackground(new Color(72,84,247));
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        btnBuscar.setBackground(new Color(53,58,196));             
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        // Obtener las fechas de inicio y fin seleccionadas
        Date fechaInicio = dateFechaInicio.getDate();
        Date fechaFin = dateFechaFin.getDate();
        if (fechaInicio != null && fechaFin != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String fechaInicioStr = dateFormat.format(fechaInicio);
            String fechaFinStr = dateFormat.format(fechaFin);
            switch (campoTabla) {
                case "Compras":
                iniTablaComprasEntreFechas(fechaInicioStr, fechaFinStr);

                    break;
                case "Ventas":

                    iniTablaVentasEntreFechas(fechaInicioStr, fechaFinStr);
                    break;
            }
           
        }else{
            // Mostrar mensaje de error si no se han seleccionado ambas fechas
            ModalNotificar modal = new ModalNotificar("Debe seleccionar ambas fechas");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }


        
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void cbxCamposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCamposItemStateChanged
        // TODO add your handling code here:
        campoTabla = cbxCampos.getSelectedItem().toString();
        switch(campoTabla){
            case "Compras":
                iniTablaCompras();
                dateFechaInicio.setEnabled(true);
                dateFechaFin.setEnabled(true);
                dateFechaInicio.getComponent(1).setEnabled(false);
                dateFechaFin.getComponent(1).setEnabled(false);
                break;
            case "Ventas":
                iniTablaVentas();
                dateFechaInicio.setEnabled(true);
                dateFechaFin.setEnabled(true);
                dateFechaInicio.getComponent(1).setEnabled(false);
                dateFechaFin.getComponent(1).setEnabled(false);
                break;
            case "Inventario":
                iniTablaArticulos();
                dateFechaInicio.setEnabled(false);
                dateFechaFin.setEnabled(false);
                break;
        }                        
 
    }//GEN-LAST:event_cbxCamposItemStateChanged

    private void btnReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseClicked
        // TODO add your handling code here:
        String nombre= (String)LoginFrame.sesionUsuario.get("nombre");
        try {
            excelUtil.construirExcel(reportesController.obtenerDatosTabla(obtenerDatosTabla()),reportesController.obtenerEncabezadosColumna(campoTabla),campoTabla,nombre);
            ModalNotificar modal = new ModalNotificar("Reporte Creado");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
            
        } catch (Exception ex) {
            Logger.getLogger(panelReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReporteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnReporte;
    private javax.swing.JComboBox<String> cbxCampos;
    private com.toedter.calendar.JDateChooser dateFechaFin;
    private com.toedter.calendar.JDateChooser dateFechaInicio;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCampos;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblReporte;
    private javax.swing.JLabel lblTituloIconArticulos;
    private javax.swing.JPanel paneBotones;
    private javax.swing.JPanel paneCampos;
    private javax.swing.JPanel paneContenedor;
    private javax.swing.JPanel paneContenidoReporte;
    private javax.swing.JPanel paneCrudReporte;
    private javax.swing.JPanel paneFechaFin;
    private javax.swing.JPanel paneFechaInicio;
    private javax.swing.JPanel paneOpcionesReporte;
    private javax.swing.JPanel paneTablaReporte;
    private javax.swing.JPanel paneTituloReporte;
    private javax.swing.JTable tblReporte;
    // End of variables declaration//GEN-END:variables

    private void iniComplementLayout() {
        getContentPane().setLayout(new CardLayout());
        
        getContentPane().add(paneContenidoReporte);
        //layaout para el contenido
        FlowLayout flowlayoutContenido = new FlowLayout(FlowLayout.CENTER,10,70);
        paneContenidoReporte.setLayout(flowlayoutContenido);
            FlowLayout flowlayoutTituloArticulos = new FlowLayout(FlowLayout.LEFT,10,10);
            paneCrudReporte.setLayout(new BorderLayout());
                paneTituloReporte.setLayout(flowlayoutTituloArticulos);
                paneCrudReporte.add(paneTituloReporte, java.awt.BorderLayout.PAGE_START);
                paneCrudReporte.add(paneContenedor, java.awt.BorderLayout.CENTER);
                    paneContenedor.setLayout(new BorderLayout());
                    paneContenedor.add(paneOpcionesReporte, java.awt.BorderLayout.PAGE_START);
                    paneContenedor.add(paneTablaReporte, java.awt.BorderLayout.CENTER);
                    
                FlowLayout flowlayoutOpArticulos= new FlowLayout(FlowLayout.RIGHT,15,10);
                paneOpcionesReporte.setLayout(flowlayoutOpArticulos);
                    paneCampos.setLayout(new BoxLayout(paneCampos, BoxLayout.Y_AXIS));
                                cbxCampos.setAlignmentX(LEFT_ALIGNMENT);
                                lblCampos.setAlignmentX(LEFT_ALIGNMENT);
                            paneCampos.add(lblCampos);     
                            paneCampos.add(cbxCampos);    
                    paneFechaInicio.setLayout(new BoxLayout(paneFechaInicio, BoxLayout.Y_AXIS));
                                dateFechaInicio.setAlignmentX(LEFT_ALIGNMENT);
                                lblFechaInicio.setAlignmentX(LEFT_ALIGNMENT);
                            paneFechaInicio.add(lblFechaInicio);     
                            paneFechaInicio.add(dateFechaInicio);    
                    paneFechaFin.setLayout(new BoxLayout(paneFechaFin, BoxLayout.Y_AXIS));
                                dateFechaFin.setAlignmentX(LEFT_ALIGNMENT);
                                lblFechaFin.setAlignmentX(LEFT_ALIGNMENT);
                            paneFechaFin.add(lblFechaFin);     
                            paneFechaFin.add(dateFechaFin);   
                    paneBotones.setLayout(null);
                    
                    
                    paneBotones.add(btnBuscar);
                    paneBotones.add(btnReporte);
                    btnBuscar.setLayout(new GridBagLayout());
                    btnReporte.setLayout(new GridBagLayout());
                    
                paneOpcionesReporte.add(paneCampos);  
                paneOpcionesReporte.add(paneFechaInicio);
                paneOpcionesReporte.add(paneFechaFin);
                paneOpcionesReporte.add(paneBotones);
        
    }

    private void iniSize() {
         //tamaño de ventana
        this.setBounds(0,0,1400, 900);
        
        //tamaño del panel de contenido
        paneContenidoReporte.setPreferredSize(new Dimension( 1, 1));    
            paneCrudReporte.setPreferredSize(new Dimension( 1000, 650));    
                paneOpcionesReporte.setPreferredSize(new Dimension( 1000, 100));  
                    paneCampos.setPreferredSize(new Dimension( 160,60 ));
                    paneFechaInicio.setPreferredSize(new Dimension( 160,60 ));
                    paneFechaFin.setPreferredSize(new Dimension( 160,60 ));
                    paneBotones.setPreferredSize(new Dimension( 330,60 ));
                    btnReporte.setPreferredSize(new Dimension( 200, 40));
                    btnBuscar.setPreferredSize(new Dimension( 130, 40));
                    
    }           
    private void iniLocation(){
        //centrando ventana
        this.setLocationRelativeTo(null);
        btnBuscar.setLocation(0, 20);
        btnReporte.setLocation(130, 20);
    }

    private void iniDiseños() {
        lblReporte.setHorizontalAlignment(SwingConstants.CENTER);
        lblReporte.setVerticalAlignment(SwingConstants.TOP);
        
        lblBuscar.setHorizontalAlignment(SwingConstants.CENTER);
        lblBuscar.setVerticalAlignment(SwingConstants.TOP);
    }
    public JPanel obtenerPanel(){
        return this.paneContenidoReporte;
    }
    private void iniTablaVentas(){
        tabla = ventaController.ObtenerVentas();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Usuario");
        model.addColumn("Nombre Cliente");
        model.addColumn("DNI Cliente");
        model.addColumn("Metodo de Pago");
        model.addColumn("Fecha de Venta");
        model.addColumn("Total");
        
        for(Map<String, Object> res : tabla){
            Map<String, Object> usuUsuario=ventaController.ObtenerNombreUsuario((Integer)res.get("idusuario"));
            model.addRow(new Object[]{res.get("id"),usuUsuario.get("usuUsuario"), res.get("NomCliente"), res.get("DNICliente"),res.get("MetodoPago"), res.get("fecha"),res.get("total")});        
        } 
        
        tblReporte.setModel(model);
        tblReporte.repaint();
    }
    private void iniTablaCompras(){
        tabla = compraController.ObtenerCompras();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Proveedor");
        model.addColumn("RUC del Proveedor");
        model.addColumn("Usuario");
        model.addColumn("Fecha");
        model.addColumn("Total");

                
        for(Map<String, Object> res : tabla){
            Map<String, Object> usuUsuario=compraController.ObtenerNombreUsuario((Integer)res.get("idUsuario"));
            Map<String, Object> nomProveedor=compraController.ObtenerNombreProveedor((Integer)res.get("idProveedor"));
            Map<String, Object>[] proveedor=compraController.ObtenerPorveedorPorNombre(nomProveedor.get("nomProveedor").toString());
            if (proveedor != null && proveedor.length > 0) {
                model.addRow(new Object[]{res.get("id"), nomProveedor.get("nomProveedor"),proveedor[0].get("ruc"),usuUsuario.get("usuUsuario"), res.get("fecha"),res.get("total")});        
            }
        } 
            
        
        tblReporte.setModel(model);
        tblReporte.repaint();
    }
    private void iniTablaArticulos(){
        tabla = articulosController.ObtenerArticulos();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("id");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Categoria");
        model.addColumn("Marca");
        model.addColumn("Stock");
        model.addColumn("Precio Unitario");

        for(Map<String, Object> res : tabla){
            Map<String, Object> nomCategoria=articulosController.ObtenerNombreCategoria((Integer)res.get("categoria"));
            Map<String, Object> nomMarca=articulosController.ObtenerNombreMarca((Integer)res.get("marca"));
            Map<String, Object>[] almacen = reportesController.ObtenerAlmacenPorIdArticulo((Integer) res.get("idArticulo"));
            if (almacen != null && almacen.length > 0) {
                model.addRow(new Object[]{res.get("idArticulo"), res.get("nombre"), res.get("descripcion"), nomCategoria.get("nomCategoria"), nomMarca.get("nomMarca"), almacen[0].get("stock"), almacen[0].get("precio")});        
            }
            
        }
        
        tblReporte.setModel(model);
        tblReporte.repaint();
    }
    public Object[][] obtenerDatosTabla() {
        int rowCount = tblReporte.getRowCount();
        int columnCount = tblReporte.getColumnCount();

        Object[][] data = new Object[rowCount][columnCount];

        for (int rowIndex = 0; rowIndex < rowCount; rowIndex++) {
            for (int columnIndex = 0; columnIndex < columnCount; columnIndex++) {
                data[rowIndex][columnIndex] = tblReporte.getValueAt(rowIndex, columnIndex);
            }
        }

        return data;
    }
    private void iniTablaVentasEntreFechas(String inicio, String fin){
        tabla = reportesController.ObtenerVentasEntreFechas(inicio, fin);
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Usuario");
        model.addColumn("Nombre Cliente");
        model.addColumn("DNI Cliente");
        model.addColumn("Metodo de Pago");
        model.addColumn("Fecha de Venta");
        model.addColumn("Total");
        
        for(Map<String, Object> res : tabla){
            Map<String, Object> usuUsuario=ventaController.ObtenerNombreUsuario((Integer)res.get("idusuario"));
            model.addRow(new Object[]{res.get("id"),usuUsuario.get("usuUsuario"), res.get("NomCliente"), res.get("DNICliente"),res.get("MetodoPago"), res.get("fecha"),res.get("total")});        
        } 
        
        tblReporte.setModel(model);
        tblReporte.repaint();
    }
    private void iniTablaComprasEntreFechas(String inicio, String fin){
        tabla = reportesController.ObtenerComprasEntreFechas(inicio, fin);
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Proveedor");
        model.addColumn("RUC del Proveedor");
        model.addColumn("Usuario");
        model.addColumn("Fecha");
        model.addColumn("Total");

                
        for(Map<String, Object> res : tabla){
            Map<String, Object> usuUsuario=compraController.ObtenerNombreUsuario((Integer)res.get("idUsuario"));
            Map<String, Object> nomProveedor=compraController.ObtenerNombreProveedor((Integer)res.get("idProveedor"));
            Map<String, Object>[] proveedor=compraController.ObtenerPorveedorPorNombre(nomProveedor.get("nomProveedor").toString());
            if (proveedor != null && proveedor.length > 0) {
                model.addRow(new Object[]{res.get("id"), nomProveedor.get("nomProveedor"),proveedor[0].get("ruc"),usuUsuario.get("usuUsuario"), res.get("fecha"),res.get("total")});        
            }
        } 
            
        
        tblReporte.setModel(model);
        tblReporte.repaint();
    }

}
