/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.AlmacenController;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author enriq
 */
public class panelAlmacen extends javax.swing.JFrame {

    /**
     * Creates new form panelArticulos
     */
    AlmacenController almacenController=new AlmacenController();
    Map<String, Object>[] tabla;
    Map<String, Object>[] Combo = almacenController.ObtenerArticulos();
    boolean editNuevo;
    int idSeleccionado;
    private JDialog dialog;
    public panelAlmacen() {
        initComponents();
        iniComplementLayout();
        iniSize();
        iniDiseños();
        iniTablaAlmacen();
        iniComboBoxArticulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneContenidoAlmacen = new javax.swing.JPanel();
        paneCrudAlmacen = new javax.swing.JPanel();
        paneTituloAlmacen = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblTituloIconArticulos = new javax.swing.JLabel();
        paneContenedor = new javax.swing.JPanel();
        paneOpcionesAlmacen = new javax.swing.JPanel();
        paneBuscar = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        lblTituloIconArticulos1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblTituloIconArticulos2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JPanel();
        lblTituloIconArticulos3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paneTablaAlmacen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlmacen = new javax.swing.JTable();
        paneModalAlmacen = new javax.swing.JPanel();
        paneContenidoVentana = new javax.swing.JPanel();
        paneAtributosAlmacen = new javax.swing.JPanel();
        paneStock = new javax.swing.JPanel();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        paneArticulo = new javax.swing.JPanel();
        lblArticulo = new javax.swing.JLabel();
        cbxArticulo = new javax.swing.JComboBox<>();
        panePreUni = new javax.swing.JPanel();
        lblPreUni = new javax.swing.JLabel();
        txtPreUni = new javax.swing.JTextField();
        paneBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        paneHeader = new javax.swing.JPanel();
        lblHeaderLogo = new javax.swing.JLabel();
        paneHeaderOpciones = new javax.swing.JPanel();
        lblCerrarVentana = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneContenidoAlmacen.setBackground(new java.awt.Color(229, 238, 255));

        paneCrudAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        paneCrudAlmacen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 4));

        paneTituloAlmacen.setBackground(new java.awt.Color(72, 84, 247));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Almacen");

        lblTituloIconArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/almacenB.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloAlmacenLayout = new javax.swing.GroupLayout(paneTituloAlmacen);
        paneTituloAlmacen.setLayout(paneTituloAlmacenLayout);
        paneTituloAlmacenLayout.setHorizontalGroup(
            paneTituloAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloAlmacenLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTituloIconArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloAlmacenLayout.setVerticalGroup(
            paneTituloAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneContenedor.setBackground(new java.awt.Color(153, 153, 153));

        paneOpcionesAlmacen.setBackground(new java.awt.Color(255, 255, 255));

        paneBuscar.setBackground(new java.awt.Color(72, 84, 247));
        paneBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 3));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(72, 84, 247));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneBuscarLayout = new javax.swing.GroupLayout(paneBuscar);
        paneBuscar.setLayout(paneBuscarLayout);
        paneBuscarLayout.setHorizontalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        paneBuscarLayout.setVerticalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnEditar.setBackground(new java.awt.Color(255, 214, 0));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        lblTituloIconArticulos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapizB.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloIconArticulos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGroup(btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloIconArticulos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btnEditarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(211, 80, 80));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarMouseMoved(evt);
            }
        });
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        lblTituloIconArticulos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basuraB.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTituloIconArticulos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnEliminarLayout.createSequentialGroup()
                        .addComponent(lblTituloIconArticulos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))))
        );

        btnNuevo.setBackground(new java.awt.Color(0, 197, 26));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNuevoMouseMoved(evt);
            }
        });
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoMouseExited(evt);
            }
        });

        lblTituloIconArticulos3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoB.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo");

        javax.swing.GroupLayout btnNuevoLayout = new javax.swing.GroupLayout(btnNuevo);
        btnNuevo.setLayout(btnNuevoLayout);
        btnNuevoLayout.setHorizontalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNuevoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloIconArticulos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnNuevoLayout.setVerticalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneOpcionesAlmacenLayout = new javax.swing.GroupLayout(paneOpcionesAlmacen);
        paneOpcionesAlmacen.setLayout(paneOpcionesAlmacenLayout);
        paneOpcionesAlmacenLayout.setHorizontalGroup(
            paneOpcionesAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOpcionesAlmacenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        paneOpcionesAlmacenLayout.setVerticalGroup(
            paneOpcionesAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOpcionesAlmacenLayout.createSequentialGroup()
                .addGroup(paneOpcionesAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        paneTablaAlmacen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        tblAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAlmacen);

        javax.swing.GroupLayout paneTablaAlmacenLayout = new javax.swing.GroupLayout(paneTablaAlmacen);
        paneTablaAlmacen.setLayout(paneTablaAlmacenLayout);
        paneTablaAlmacenLayout.setHorizontalGroup(
            paneTablaAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        paneTablaAlmacenLayout.setVerticalGroup(
            paneTablaAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneContenedorLayout = new javax.swing.GroupLayout(paneContenedor);
        paneContenedor.setLayout(paneContenedorLayout);
        paneContenedorLayout.setHorizontalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneTablaAlmacen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneOpcionesAlmacen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneContenedorLayout.setVerticalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addComponent(paneOpcionesAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(paneTablaAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneCrudAlmacenLayout = new javax.swing.GroupLayout(paneCrudAlmacen);
        paneCrudAlmacen.setLayout(paneCrudAlmacenLayout);
        paneCrudAlmacenLayout.setHorizontalGroup(
            paneCrudAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneCrudAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneCrudAlmacenLayout.setVerticalGroup(
            paneCrudAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCrudAlmacenLayout.createSequentialGroup()
                .addComponent(paneTituloAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoAlmacenLayout = new javax.swing.GroupLayout(paneContenidoAlmacen);
        paneContenidoAlmacen.setLayout(paneContenidoAlmacenLayout);
        paneContenidoAlmacenLayout.setHorizontalGroup(
            paneContenidoAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoAlmacenLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(paneCrudAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneContenidoAlmacenLayout.setVerticalGroup(
            paneContenidoAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoAlmacenLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(paneCrudAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        paneModalAlmacen.setBackground(new java.awt.Color(255, 255, 255));

        paneContenidoVentana.setOpaque(false);

        paneAtributosAlmacen.setBackground(new java.awt.Color(204, 204, 204));
        paneAtributosAlmacen.setOpaque(false);

        paneStock.setOpaque(false);

        lblStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStock.setText("Stock");

        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneStockLayout = new javax.swing.GroupLayout(paneStock);
        paneStock.setLayout(paneStockLayout);
        paneStockLayout.setHorizontalGroup(
            paneStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneStockLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(paneStockLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneStockLayout.setVerticalGroup(
            paneStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneStockLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        paneArticulo.setOpaque(false);

        lblArticulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArticulo.setText("Articulo");

        javax.swing.GroupLayout paneArticuloLayout = new javax.swing.GroupLayout(paneArticulo);
        paneArticulo.setLayout(paneArticuloLayout);
        paneArticuloLayout.setHorizontalGroup(
            paneArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneArticuloLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(paneArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArticulo)
                    .addComponent(cbxArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        paneArticuloLayout.setVerticalGroup(
            paneArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneArticuloLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panePreUni.setOpaque(false);

        lblPreUni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPreUni.setText("Precio Unitario");

        txtPreUni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPreUni.setToolTipText("");

        javax.swing.GroupLayout panePreUniLayout = new javax.swing.GroupLayout(panePreUni);
        panePreUni.setLayout(panePreUniLayout);
        panePreUniLayout.setHorizontalGroup(
            panePreUniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePreUniLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panePreUniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPreUni)
                    .addComponent(txtPreUni, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panePreUniLayout.setVerticalGroup(
            panePreUniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePreUniLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblPreUni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPreUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneAtributosAlmacenLayout = new javax.swing.GroupLayout(paneAtributosAlmacen);
        paneAtributosAlmacen.setLayout(paneAtributosAlmacenLayout);
        paneAtributosAlmacenLayout.setHorizontalGroup(
            paneAtributosAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAtributosAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panePreUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneAtributosAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(paneArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        paneAtributosAlmacenLayout.setVerticalGroup(
            paneAtributosAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAtributosAlmacenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panePreUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );

        paneBotones.setOpaque(false);

        btnCancelar.setBackground(new java.awt.Color(102, 102, 255));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCancelarMouseMoved(evt);
            }
        });
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(102, 102, 255));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnGuardarMouseMoved(evt);
            }
        });
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoVentanaLayout = new javax.swing.GroupLayout(paneContenidoVentana);
        paneContenidoVentana.setLayout(paneContenidoVentanaLayout);
        paneContenidoVentanaLayout.setHorizontalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(paneAtributosAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneContenidoVentanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneContenidoVentanaLayout.setVerticalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneAtributosAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        paneHeader.setBackground(new java.awt.Color(25, 34, 143));

        lblHeaderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        paneHeaderOpciones.setBackground(new java.awt.Color(27, 39, 187));
        paneHeaderOpciones.setOpaque(false);

        lblCerrarVentana.setBackground(new java.awt.Color(255, 58, 97));
        lblCerrarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarVentana.png"))); // NOI18N
        lblCerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCerrarVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseMoved(evt);
            }
        });
        lblCerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneHeaderOpcionesLayout = new javax.swing.GroupLayout(paneHeaderOpciones);
        paneHeaderOpciones.setLayout(paneHeaderOpcionesLayout);
        paneHeaderOpcionesLayout.setHorizontalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderOpcionesLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(lblCerrarVentana)
                .addGap(48, 48, 48))
        );
        paneHeaderOpcionesLayout.setVerticalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderOpcionesLayout.createSequentialGroup()
                .addComponent(lblCerrarVentana)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Nuevo Almacen");
        lbltitulo.setToolTipText("");

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHeaderLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHeaderLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                        .addComponent(lbltitulo)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout paneModalAlmacenLayout = new javax.swing.GroupLayout(paneModalAlmacen);
        paneModalAlmacen.setLayout(paneModalAlmacenLayout);
        paneModalAlmacenLayout.setHorizontalGroup(
            paneModalAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 466, Short.MAX_VALUE)
            .addGroup(paneModalAlmacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        paneModalAlmacenLayout.setVerticalGroup(
            paneModalAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModalAlmacenLayout.createSequentialGroup()
                .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 935, Short.MAX_VALUE)
                .addGap(769, 769, 769))
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(paneModalAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(905, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paneModalAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        // TODO add your handling code here:
        Color Micolor= new Color(0,0,204);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        Color Micolor= new Color(72,84,247);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(255,227,82));
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(255,214,0));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseMoved
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(249,98,98));
    }//GEN-LAST:event_btnEliminarMouseMoved

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(228,77,77));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnNuevoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseMoved
        // TODO add your handling code here:
        btnNuevo.setBackground(new Color(0,222,29));
    }//GEN-LAST:event_btnNuevoMouseMoved

    private void btnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseExited
        // TODO add your handling code here:
        btnNuevo.setBackground(new Color(0,197,26));
    }//GEN-LAST:event_btnNuevoMouseExited

    private void btnCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseMoved
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(62,62,241));
    }//GEN-LAST:event_btnCancelarMouseMoved

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255));
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtStock.setText("");
        txtPreUni.setText("");
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseMoved
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(62,62,241));
    }//GEN-LAST:event_btnGuardarMouseMoved

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(102,102,255));
        if(editNuevo){
            Guardar();
        }else{
            Editar(idSeleccionado);
        }
        
        txtStock.setText("");
        txtPreUni.setText("");
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        iniTablaAlmacen();
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void lblCerrarVentanaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseMoved
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(true);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseMoved

    private void lblCerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseClicked
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtStock.setText("");
        txtPreUni.setText("");
    }//GEN-LAST:event_lblCerrarVentanaMouseClicked

    private void lblCerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseExited
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseExited

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        // TODO add your handling code here:
        editNuevo=true;
        NuevoModalAlmacen();
        dialog.setLocationRelativeTo(null); // centra el dialogo en la pantalla
        dialog.setVisible(true);
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        
        TableModel model = tblAlmacen.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblAlmacen.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            // Obtiene los valores de las columnas de la fila seleccionada
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna
            Object value2 = model.getValueAt(selectedRow, 1); // Valor de la primera columna
            Object value3 = model.getValueAt(selectedRow, 2); // Valor de la primera columna
            Object value4 = model.getValueAt(selectedRow, 3); // Valor de la primera columna
            
            int idAlmacen = Integer.parseInt(value1.toString());
            
            for (int i = 0; i < cbxArticulo.getItemCount(); i++) {
                String elemento = cbxArticulo.getItemAt(i);
                if (elemento.equals(value2.toString())) {
                    // Se encontró el elemento con el nombre deseado, se selecciona
                    cbxArticulo.setSelectedIndex(i);
                    break;
                }
            }
            
            cbxArticulo.getSelectedItem().toString();
            txtPreUni.setText(value4.toString());
            txtStock.setText(value3.toString());
            
            idSeleccionado=idAlmacen;
            editNuevo=false;
            EditarModalAlmacen();
            dialog.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialog.setVisible(true);
            
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        TableModel model = tblAlmacen.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblAlmacen.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna   
            int idAlmacen = Integer.parseInt(value1.toString());
            
            Eliminar(idAlmacen);
            
        }
        iniTablaAlmacen();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        iniTablaAlmacen();
        String elementoBusqueda = txtBusqueda.getText(); // Elemento que se desea buscar
        if(!elementoBusqueda.equals("")){
            DefaultTableModel model = (DefaultTableModel) tblAlmacen.getModel();
            int rowCount = model.getRowCount();
            int columnCount = model.getColumnCount();

            List<Integer> filasCoincidentes = new ArrayList<>();

            for (int row = 0; row < rowCount; row++) {
                for (int column = 0; column < columnCount; column++) {
                    Object cellValue = model.getValueAt(row, column);
                    String cellString = String.valueOf(cellValue);

                    if (cellString.equals(elementoBusqueda)) {
                        filasCoincidentes.add(row);
                        // Puedes realizar alguna acción adicional, como resaltar la fila
                    }
                }
            }
            DefaultTableModel modelAlmacen = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            modelAlmacen.addColumn("id");
            modelAlmacen.addColumn("Articulo");
            modelAlmacen.addColumn("Stock");
            modelAlmacen.addColumn("Precio Unitario");

            for (Integer filaCoincidente : filasCoincidentes) {
                Object[] rowData = new Object[4];
                rowData[0] = tblAlmacen.getValueAt(filaCoincidente, 0);  // id_almacen
                rowData[1] = tblAlmacen.getValueAt(filaCoincidente, 1);  // id_articulo
                rowData[2] = tblAlmacen.getValueAt(filaCoincidente, 2);  // stock
                rowData[3] = tblAlmacen.getValueAt(filaCoincidente, 3);  // precio_unitario
                System.out.println(rowData[3]);
                modelAlmacen.addRow(rowData);
            }
      
            tblAlmacen.setModel(modelAlmacen);
            tblAlmacen.repaint();
        }else{
            iniTablaAlmacen();
        }
        
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelAlmacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnNuevo;
    private javax.swing.JComboBox<String> cbxArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArticulo;
    private javax.swing.JLabel lblCerrarVentana;
    private javax.swing.JLabel lblHeaderLogo;
    private javax.swing.JLabel lblPreUni;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTituloIconArticulos;
    private javax.swing.JLabel lblTituloIconArticulos1;
    private javax.swing.JLabel lblTituloIconArticulos2;
    private javax.swing.JLabel lblTituloIconArticulos3;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel paneArticulo;
    private javax.swing.JPanel paneAtributosAlmacen;
    private javax.swing.JPanel paneBotones;
    private javax.swing.JPanel paneBuscar;
    private javax.swing.JPanel paneContenedor;
    private javax.swing.JPanel paneContenidoAlmacen;
    private javax.swing.JPanel paneContenidoVentana;
    private javax.swing.JPanel paneCrudAlmacen;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JPanel paneHeaderOpciones;
    private javax.swing.JPanel paneModalAlmacen;
    private javax.swing.JPanel paneOpcionesAlmacen;
    private javax.swing.JPanel panePreUni;
    private javax.swing.JPanel paneStock;
    private javax.swing.JPanel paneTablaAlmacen;
    private javax.swing.JPanel paneTituloAlmacen;
    private javax.swing.JTable tblAlmacen;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtPreUni;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    private void iniComplementLayout() {
        getContentPane().setLayout(new CardLayout());
        
        getContentPane().add(paneContenidoAlmacen);
        getContentPane().remove(paneModalAlmacen);
        //layaout para el contenido
        FlowLayout flowlayoutContenido = new FlowLayout(FlowLayout.CENTER,10,70);
        paneContenidoAlmacen.setLayout(flowlayoutContenido);
            FlowLayout flowlayoutTituloArticulos = new FlowLayout(FlowLayout.LEFT,10,10);
            paneCrudAlmacen.setLayout(new BorderLayout());
                paneTituloAlmacen.setLayout(flowlayoutTituloArticulos);
                paneCrudAlmacen.add(paneTituloAlmacen, java.awt.BorderLayout.PAGE_START);
                paneCrudAlmacen.add(paneContenedor, java.awt.BorderLayout.CENTER);
                    paneContenedor.setLayout(new BorderLayout());
                    paneContenedor.add(paneOpcionesAlmacen, java.awt.BorderLayout.PAGE_START);
                    paneContenedor.add(paneTablaAlmacen, java.awt.BorderLayout.CENTER);
                    
                FlowLayout flowlayoutOpArticulos= new FlowLayout(FlowLayout.RIGHT,15,30);
                paneOpcionesAlmacen.setLayout(flowlayoutOpArticulos);
                    FlowLayout flowlayoutBoton = new FlowLayout(FlowLayout.CENTER,10,8);
                    paneBuscar.setLayout(new BoxLayout(paneBuscar, BoxLayout.X_AXIS));
                    //btnEditar.setLayout(flowlayoutBoton);
                    //btnEliminar.setLayout(flowlayoutBoton);
                    btnNuevo.setLayout(flowlayoutBoton);
                    btnEditar.setLayout(flowlayoutBoton);
                    btnEliminar.setLayout(flowlayoutBoton);
        //modal nuevo
        //layout de la ventana  
         paneModalAlmacen.setLayout(new BorderLayout());

         paneModalAlmacen.add(paneContenidoVentana, java.awt.BorderLayout.CENTER);
         paneModalAlmacen.add(paneHeader, java.awt.BorderLayout.PAGE_START);

          //layout de header de la ventana
         paneHeader.setLayout(new BoxLayout(paneHeader, BoxLayout.X_AXIS));

         FlowLayout flowlayoutHeaderOpciones = new FlowLayout(FlowLayout.RIGHT,0,0);
         paneHeaderOpciones.setLayout(flowlayoutHeaderOpciones);
         paneHeader.add(lblHeaderLogo);
         paneHeader.add(lbltitulo);
         paneHeader.add(Box.createHorizontalGlue()); // Espaciador flexible
         paneHeader.add(paneHeaderOpciones);
         //contenido del modal
         
         //contenerdo de los atributos
         paneContenidoVentana.setLayout(new BorderLayout());
         paneContenidoVentana.add(paneAtributosAlmacen, java.awt.BorderLayout.CENTER);
         paneContenidoVentana.add(paneBotones, java.awt.BorderLayout.PAGE_END);
         FlowLayout flowlayoutAtributosUsuario = new FlowLayout(FlowLayout.CENTER,10,30);
         paneAtributosAlmacen.setLayout(flowlayoutAtributosUsuario);
            //contenedor de los txt y label
            paneArticulo.setLayout(new BoxLayout(paneArticulo, BoxLayout.Y_AXIS));
                cbxArticulo.setAlignmentX(LEFT_ALIGNMENT);
                lblArticulo.setAlignmentX(LEFT_ALIGNMENT);
                paneArticulo.add(lblArticulo);     
                paneArticulo.add(cbxArticulo); 
            paneStock.setLayout(new BoxLayout(paneStock, BoxLayout.Y_AXIS));
                txtStock.setAlignmentX(LEFT_ALIGNMENT);
                lblStock.setAlignmentX(LEFT_ALIGNMENT);
                paneStock.add(lblStock);     
                paneStock.add(txtStock); 
            panePreUni.setLayout(new BoxLayout(panePreUni, BoxLayout.Y_AXIS));
                txtPreUni.setAlignmentX(LEFT_ALIGNMENT);
                lblPreUni.setAlignmentX(LEFT_ALIGNMENT);
                panePreUni.add(lblPreUni);     
                panePreUni.add(txtPreUni); 
        paneAtributosAlmacen.add(paneArticulo);
        paneAtributosAlmacen.add(paneStock);
        paneAtributosAlmacen.add(panePreUni);
        
        
        FlowLayout flowlayoutBotones = new FlowLayout(FlowLayout.CENTER,30,10);
        paneBotones.setLayout(flowlayoutBotones);
        btnGuardar.setLayout(new GridBagLayout());
        btnCancelar.setLayout(new GridBagLayout());
    }

    private void iniSize() {
         //tamaño de ventana
        this.setBounds(0,0,1400, 900);
        
        //tamaño del panel de contenido
        paneContenidoAlmacen.setPreferredSize(new Dimension( 1, 1));    
            paneCrudAlmacen.setPreferredSize(new Dimension( 1000, 650));    
                paneOpcionesAlmacen.setPreferredSize(new Dimension( 1000, 100));  
                //paneTablaArticulos.setPreferredSize(new Dimension( 1000, 100));  
                    txtBusqueda.setPreferredSize(new Dimension( 200, 40));
                    btnBuscar.setPreferredSize(new Dimension( 60, 40));
                    btnNuevo.setPreferredSize(new Dimension( 200, 40));
                    btnEditar.setPreferredSize(new Dimension( 200, 40));
                    btnEliminar.setPreferredSize(new Dimension( 200, 40));
        //modal
            //tamaño del panel header
            paneHeader.setPreferredSize(new Dimension( 1, 40));
            lblHeaderLogo.setSize(new Dimension( 40, 40));
            lblCerrarVentana.setPreferredSize(new Dimension( 40, 40));
            
            //tamaño del contenido
            paneAtributosAlmacen.setPreferredSize(new Dimension(380,60));
            paneArticulo.setPreferredSize(new Dimension(380,60));
            paneStock.setPreferredSize(new Dimension(380,60));
            panePreUni.setPreferredSize(new Dimension(380,60));
            
            paneBotones.setPreferredSize(new Dimension(450,80));
            btnGuardar.setPreferredSize(new Dimension(150,40));
            btnCancelar.setPreferredSize(new Dimension(150,40));
    }


    private void iniDiseños() {
        //modal
            //inicaiar imagenes del Header de la ventana.
            redimencionarImagenen(lblHeaderLogo,"/img/logo.png");       
            lblCerrarVentana.setVerticalAlignment(SwingConstants.CENTER);
            lblCerrarVentana.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    public JPanel obtenerPanel(){
        return this.paneContenidoAlmacen;
    }
    
    public void redimencionarImagenen(JLabel lblicon,String img){
      // Cargamos la imagen desde un archivo
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource(img));//"/Img/login2.jpg"

        // Ajustamos el tamaño de la imagen al tamaño del JLabel
        Image image = icon.getImage();
        Image scaledImage = image.getScaledInstance(lblicon.getWidth(), lblicon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Establecemos la imagen en el JLabel                
            
        ///labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.jpg"))); 
        lblicon.setIcon(scaledIcon);    
    }
    private void NuevoModalAlmacen(){
        
        lbltitulo.setText("Nuevo Almacen");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalAlmacen); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,450)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    private void EditarModalAlmacen(){
        
        lbltitulo.setText("Modificar Almacen");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalAlmacen); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,450)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    private void iniTablaAlmacen(){
        tabla = almacenController.ObtenerAlmacenes();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("id");
        model.addColumn("Articulo");
        model.addColumn("Stock");
        model.addColumn("Precio Unitario");
        
        for(Map<String, Object> res : tabla){
            Map<String, Object> nomArticulo=almacenController.ObtenerNombreArticulo((Integer)res.get("idArticulo"));
            model.addRow(new Object[]{res.get("idAlmacen"), nomArticulo.get("nomArticulo"), res.get("stock"),res.get("precio")});        
        } 
        
        tblAlmacen.setModel(model);
        tblAlmacen.repaint();
    }
    private void iniComboBoxArticulos(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Map<String, Object> res : Combo){
           model.addElement(res.get("nombre"));      
        }
        cbxArticulo.setModel(model);
        
    }
    private void Guardar(){
        String nomArticulo=cbxArticulo.getSelectedItem().toString();
        float precio=Float.parseFloat(txtPreUni.getText());
        int stock= Integer.parseInt(txtStock.getText());
                
        if(almacenController.registrarAlmacen(nomArticulo, precio, stock)){
            ModalNotificar modal = new ModalNotificar("Guardado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
    }
    private void Editar(int id){
        String nomArticulo=cbxArticulo.getSelectedItem().toString();
        float precio=Float.parseFloat(txtPreUni.getText());
        int stock= Integer.parseInt(txtStock.getText());


        if(almacenController.actualizarAlmacen(id,nomArticulo, precio, stock)){
            ModalNotificar modal = new ModalNotificar("Actualizado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
        
    }
    private void Eliminar(int id){

        if(almacenController.EliminarAlmace(id)){
            ModalNotificar modal = new ModalNotificar("Eliminado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
        
    }
}
