/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.ArticulosController;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author enriq
 */
public class panelArticulos extends javax.swing.JFrame {

    /**
     * Creates new form panelArticulos
     */
    ArticulosController articulosController=new ArticulosController();
    Map<String, Object>[] tabla;
    Map<String, Object>[] ComboMar = articulosController.ObtenerMarcas();
    Map<String, Object>[] ComboCat = articulosController.ObtenerCategorias();
    boolean editNuevo = true;
    int idSeleccionado;
    public JDialog dialog; // true indica que es modal
    public panelArticulos() {
        initComponents();
        iniComplementLayout();
        iniSize();
        iniDiseños();
        iniTablaArticulos();
        iniComboBoxs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneContenidoArticulos = new javax.swing.JPanel();
        paneCrudArticulos = new javax.swing.JPanel();
        paneTituloArticulos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblTituloIconArticulos = new javax.swing.JLabel();
        paneContenedor = new javax.swing.JPanel();
        paneOpcionesArticulos = new javax.swing.JPanel();
        paneBuscar = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        lblTituloIconArticulos1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        lblTituloIconArticulos2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paneTablaArticulos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();
        paneModalArticulo = new javax.swing.JPanel();
        paneContenidoVentana = new javax.swing.JPanel();
        paneAtributosArticulo = new javax.swing.JPanel();
        paneCategoria = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        paneDescripcion = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        paneNombre = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        paneMarca = new javax.swing.JPanel();
        lblMarca = new javax.swing.JLabel();
        cbxMarca = new javax.swing.JComboBox<>();
        panePrecio = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        paneBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        paneHeader = new javax.swing.JPanel();
        lblHeaderLogo = new javax.swing.JLabel();
        paneHeaderOpciones = new javax.swing.JPanel();
        lblCerrarVentana = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneContenidoArticulos.setBackground(new java.awt.Color(229, 238, 255));

        paneCrudArticulos.setBackground(new java.awt.Color(255, 255, 255));
        paneCrudArticulos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 4));

        paneTituloArticulos.setBackground(new java.awt.Color(72, 84, 247));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Articulos");

        lblTituloIconArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/articulo.png"))); // NOI18N

        javax.swing.GroupLayout paneTituloArticulosLayout = new javax.swing.GroupLayout(paneTituloArticulos);
        paneTituloArticulos.setLayout(paneTituloArticulosLayout);
        paneTituloArticulosLayout.setHorizontalGroup(
            paneTituloArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloArticulosLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTituloIconArticulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneTituloArticulosLayout.setVerticalGroup(
            paneTituloArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTituloArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTituloArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloIconArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneContenedor.setBackground(new java.awt.Color(153, 153, 153));

        paneOpcionesArticulos.setBackground(new java.awt.Color(255, 255, 255));

        paneBuscar.setBackground(new java.awt.Color(72, 84, 247));
        paneBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 84, 247), 3));

        txtBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(72, 84, 247));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneBuscarLayout = new javax.swing.GroupLayout(paneBuscar);
        paneBuscar.setLayout(paneBuscarLayout);
        paneBuscarLayout.setHorizontalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        paneBuscarLayout.setVerticalGroup(
            paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnEditar.setBackground(new java.awt.Color(21, 209, 46));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });

        lblTituloIconArticulos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapizB.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar");

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloIconArticulos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditarLayout.createSequentialGroup()
                .addGroup(btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloIconArticulos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, btnEditarLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(228, 77, 77));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarMouseMoved(evt);
            }
        });
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        lblTituloIconArticulos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basuraB.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar");

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTituloIconArticulos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnEliminarLayout.createSequentialGroup()
                        .addComponent(lblTituloIconArticulos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))))
        );

        javax.swing.GroupLayout paneOpcionesArticulosLayout = new javax.swing.GroupLayout(paneOpcionesArticulos);
        paneOpcionesArticulos.setLayout(paneOpcionesArticulosLayout);
        paneOpcionesArticulosLayout.setHorizontalGroup(
            paneOpcionesArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOpcionesArticulosLayout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        paneOpcionesArticulosLayout.setVerticalGroup(
            paneOpcionesArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOpcionesArticulosLayout.createSequentialGroup()
                .addGroup(paneOpcionesArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        paneTablaArticulos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblArticulos);

        javax.swing.GroupLayout paneTablaArticulosLayout = new javax.swing.GroupLayout(paneTablaArticulos);
        paneTablaArticulos.setLayout(paneTablaArticulosLayout);
        paneTablaArticulosLayout.setHorizontalGroup(
            paneTablaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        paneTablaArticulosLayout.setVerticalGroup(
            paneTablaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneContenedorLayout = new javax.swing.GroupLayout(paneContenedor);
        paneContenedor.setLayout(paneContenedorLayout);
        paneContenedorLayout.setHorizontalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneTablaArticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneOpcionesArticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneContenedorLayout.setVerticalGroup(
            paneContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenedorLayout.createSequentialGroup()
                .addComponent(paneOpcionesArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(paneTablaArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paneCrudArticulosLayout = new javax.swing.GroupLayout(paneCrudArticulos);
        paneCrudArticulos.setLayout(paneCrudArticulosLayout);
        paneCrudArticulosLayout.setHorizontalGroup(
            paneCrudArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneTituloArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneCrudArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneCrudArticulosLayout.setVerticalGroup(
            paneCrudArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCrudArticulosLayout.createSequentialGroup()
                .addComponent(paneTituloArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoArticulosLayout = new javax.swing.GroupLayout(paneContenidoArticulos);
        paneContenidoArticulos.setLayout(paneContenidoArticulosLayout);
        paneContenidoArticulosLayout.setHorizontalGroup(
            paneContenidoArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoArticulosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(paneCrudArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        paneContenidoArticulosLayout.setVerticalGroup(
            paneContenidoArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoArticulosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(paneCrudArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        paneModalArticulo.setBackground(new java.awt.Color(255, 255, 255));

        paneContenidoVentana.setOpaque(false);

        paneAtributosArticulo.setBackground(new java.awt.Color(204, 204, 204));
        paneAtributosArticulo.setOpaque(false);

        paneCategoria.setOpaque(false);

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategoria.setText("Categoria");

        cbxCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneCategoriaLayout = new javax.swing.GroupLayout(paneCategoria);
        paneCategoria.setLayout(paneCategoriaLayout);
        paneCategoriaLayout.setHorizontalGroup(
            paneCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCategoriaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(paneCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategoria)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        paneCategoriaLayout.setVerticalGroup(
            paneCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCategoriaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        paneDescripcion.setOpaque(false);

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDescripcion.setText("Descripcion");

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout paneDescripcionLayout = new javax.swing.GroupLayout(paneDescripcion);
        paneDescripcion.setLayout(paneDescripcionLayout);
        paneDescripcionLayout.setHorizontalGroup(
            paneDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneDescripcionLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(paneDescripcionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblDescripcion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneDescripcionLayout.setVerticalGroup(
            paneDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneDescripcionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        paneNombre.setOpaque(false);

        txtnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnombre.setText("Nombre ");

        javax.swing.GroupLayout paneNombreLayout = new javax.swing.GroupLayout(paneNombre);
        paneNombre.setLayout(paneNombreLayout);
        paneNombreLayout.setHorizontalGroup(
            paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNombreLayout.createSequentialGroup()
                .addGroup(paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneNombreLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblnombre))
                    .addGroup(paneNombreLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        paneNombreLayout.setVerticalGroup(
            paneNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNombreLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneMarca.setOpaque(false);

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarca.setText("Marca");

        javax.swing.GroupLayout paneMarcaLayout = new javax.swing.GroupLayout(paneMarca);
        paneMarca.setLayout(paneMarcaLayout);
        paneMarcaLayout.setHorizontalGroup(
            paneMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMarcaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(paneMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarca)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        paneMarcaLayout.setVerticalGroup(
            paneMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMarcaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panePrecio.setOpaque(false);

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setText("Precio");

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panePrecioLayout = new javax.swing.GroupLayout(panePrecio);
        panePrecio.setLayout(panePrecioLayout);
        panePrecioLayout.setHorizontalGroup(
            panePrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePrecioLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(panePrecioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblPrecio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panePrecioLayout.setVerticalGroup(
            panePrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePrecioLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneAtributosArticuloLayout = new javax.swing.GroupLayout(paneAtributosArticulo);
        paneAtributosArticulo.setLayout(paneAtributosArticuloLayout);
        paneAtributosArticuloLayout.setHorizontalGroup(
            paneAtributosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAtributosArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneAtributosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneAtributosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(paneMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneAtributosArticuloLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(paneNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        paneAtributosArticuloLayout.setVerticalGroup(
            paneAtributosArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAtributosArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );

        paneBotones.setOpaque(false);

        btnCancelar.setBackground(new java.awt.Color(102, 102, 255));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCancelarMouseMoved(evt);
            }
        });
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(102, 102, 255));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnGuardarMouseMoved(evt);
            }
        });
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneBotonesLayout = new javax.swing.GroupLayout(paneBotones);
        paneBotones.setLayout(paneBotonesLayout);
        paneBotonesLayout.setHorizontalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        paneBotonesLayout.setVerticalGroup(
            paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBotonesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paneBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneContenidoVentanaLayout = new javax.swing.GroupLayout(paneContenidoVentana);
        paneContenidoVentana.setLayout(paneContenidoVentanaLayout);
        paneContenidoVentanaLayout.setHorizontalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneAtributosArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        paneContenidoVentanaLayout.setVerticalGroup(
            paneContenidoVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneContenidoVentanaLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(paneAtributosArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paneHeader.setBackground(new java.awt.Color(25, 34, 143));

        lblHeaderLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        paneHeaderOpciones.setBackground(new java.awt.Color(27, 39, 187));
        paneHeaderOpciones.setOpaque(false);

        lblCerrarVentana.setBackground(new java.awt.Color(255, 58, 97));
        lblCerrarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarVentana.png"))); // NOI18N
        lblCerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrarVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseMoved(evt);
            }
        });
        lblCerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarVentanaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneHeaderOpcionesLayout = new javax.swing.GroupLayout(paneHeaderOpciones);
        paneHeaderOpciones.setLayout(paneHeaderOpcionesLayout);
        paneHeaderOpcionesLayout.setHorizontalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderOpcionesLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(lblCerrarVentana)
                .addGap(48, 48, 48))
        );
        paneHeaderOpcionesLayout.setVerticalGroup(
            paneHeaderOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderOpcionesLayout.createSequentialGroup()
                .addComponent(lblCerrarVentana)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setText("Nuevo Articulo");
        lbltitulo.setToolTipText("");

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHeaderLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHeaderLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHeaderLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(paneHeaderOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                        .addComponent(lbltitulo)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout paneModalArticuloLayout = new javax.swing.GroupLayout(paneModalArticulo);
        paneModalArticulo.setLayout(paneModalArticuloLayout);
        paneModalArticuloLayout.setHorizontalGroup(
            paneModalArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(paneModalArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneModalArticuloLayout.setVerticalGroup(
            paneModalArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneModalArticuloLayout.createSequentialGroup()
                .addComponent(paneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneContenidoVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(paneModalArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneContenidoArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(paneModalArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        // TODO add your handling code here:
        Color Micolor= new Color(0,0,204);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        // TODO add your handling code here:
        Color Micolor= new Color(72,84,247);
        btnBuscar.setBackground(Micolor);
        paneBuscar.setBorder(new LineBorder(Micolor,3));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(65,239,88));
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(21,209,46));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseMoved
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(249,98,98));
    }//GEN-LAST:event_btnEliminarMouseMoved

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(228,77,77));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseMoved
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(62,62,241));
    }//GEN-LAST:event_btnCancelarMouseMoved

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255));
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtnombre.setText("");
        txtDescripcion.setText("");
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        // TODO add your handling code here:
        btnCancelar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnGuardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseMoved
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(62,62,241));
    }//GEN-LAST:event_btnGuardarMouseMoved

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(102,102,255));
        if(editNuevo){
            Guardar();
        }else{
            Editar(idSeleccionado);
        }
        
        txtnombre.setText("");
        txtDescripcion.setText("");
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        iniTablaArticulos();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        // TODO add your handling code here:
        btnGuardar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void lblCerrarVentanaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseMoved
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(true);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseMoved

    private void lblCerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseClicked
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
        dialog.dispose(); // Cierra la ventana
        dialog.setVisible(false); // Oculta la ventana
        txtnombre.setText("");
        txtDescripcion.setText("");
    }//GEN-LAST:event_lblCerrarVentanaMouseClicked

    private void lblCerrarVentanaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarVentanaMouseExited
        // TODO add your handling code here:
        lblCerrarVentana.setOpaque(false);
        lblCerrarVentana.repaint();
    }//GEN-LAST:event_lblCerrarVentanaMouseExited

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        TableModel model = tblArticulos.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblArticulos.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            // Obtiene los valores de las columnas de la fila seleccionada
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna
            Object value2 = model.getValueAt(selectedRow, 1); // Valor de la primera columna
            Object value3 = model.getValueAt(selectedRow, 2); // Valor de la primera columna
            Object value4 = model.getValueAt(selectedRow, 3); // Valor de la primera columna
            Object value5 = model.getValueAt(selectedRow, 4); // Valor de la primera columna
            
            int idArticulo = Integer.parseInt(value1.toString());
            
            for (int i = 0; i < cbxCategoria.getItemCount(); i++) {
                String elemento = cbxCategoria.getItemAt(i);
                if (elemento.equals(value4.toString())) {
                    // Se encontró el elemento con el nombre deseado, se selecciona
                    cbxCategoria.setSelectedIndex(i);
                    break;
                }
            }
            for (int i = 0; i < cbxMarca.getItemCount(); i++) {
                String elemento = cbxMarca.getItemAt(i);
                if (elemento.equals(value5.toString())) {
                    // Se encontró el elemento con el nombre deseado, se selecciona
                    cbxMarca.setSelectedIndex(i);
                    break;
                }
            }
            txtnombre.setText(value2.toString());
            txtDescripcion.setText(value3.toString());
            
            idSeleccionado=idArticulo;
            editNuevo=false;
            EditarModalArticulo();
            dialog.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialog.setVisible(true);
            
        }
    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
       TableModel model = tblArticulos.getModel();

        // Verifica si hay una fila seleccionada
        int selectedRow = tblArticulos.getSelectedRow();
        
        if (selectedRow == -1) {
            ModalError modal = new ModalError("No hay fila seleccionada");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }
        else{
            
            Object value1 = model.getValueAt(selectedRow, 0); // Valor de la primera columna   
            int idArticulos = Integer.parseInt(value1.toString());
            
            Eliminar(idArticulos);
            
        }
        iniTablaArticulos();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        iniTablaArticulos();
        String elementoBusqueda = txtBusqueda.getText(); // Elemento que se desea buscar
        if(!elementoBusqueda.equals("")){
            DefaultTableModel model = (DefaultTableModel) tblArticulos.getModel();
            int rowCount = model.getRowCount();
            int columnCount = model.getColumnCount();

            List<Integer> filasCoincidentes = new ArrayList<>();

            for (int row = 0; row < rowCount; row++) {
                for (int column = 0; column < columnCount; column++) {
                    Object cellValue = model.getValueAt(row, column);
                    String cellString = String.valueOf(cellValue);

                    if (cellString.equals(elementoBusqueda)) {
                        filasCoincidentes.add(row);
                        // Puedes realizar alguna acción adicional, como resaltar la fila
                    }
                }
            }
            DefaultTableModel modelArticulo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            modelArticulo.addColumn("id");
            modelArticulo.addColumn("Nombre");
            modelArticulo.addColumn("Descripcion");
            modelArticulo.addColumn("Categoria");
            modelArticulo.addColumn("Marca");

            for (Integer filaCoincidente : filasCoincidentes) {
                Object[] rowData = new Object[5];
                rowData[0] = tblArticulos.getValueAt(filaCoincidente, 0);  // id_almacen
                rowData[1] = tblArticulos.getValueAt(filaCoincidente, 1);  // id_articulo
                rowData[2] = tblArticulos.getValueAt(filaCoincidente, 2);  // stock
                rowData[3] = tblArticulos.getValueAt(filaCoincidente, 3);  // precio_unitario
                rowData[4] = tblArticulos.getValueAt(filaCoincidente, 4);  // precio_unitario
                modelArticulo.addRow(rowData);
            }
      
            tblArticulos.setModel(modelArticulo);
            tblArticulos.repaint();
        }else{
            iniTablaArticulos();
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCerrarVentana;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblHeaderLogo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTituloIconArticulos;
    private javax.swing.JLabel lblTituloIconArticulos1;
    private javax.swing.JLabel lblTituloIconArticulos2;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel paneAtributosArticulo;
    private javax.swing.JPanel paneBotones;
    private javax.swing.JPanel paneBuscar;
    private javax.swing.JPanel paneCategoria;
    private javax.swing.JPanel paneContenedor;
    private javax.swing.JPanel paneContenidoArticulos;
    private javax.swing.JPanel paneContenidoVentana;
    private javax.swing.JPanel paneCrudArticulos;
    private javax.swing.JPanel paneDescripcion;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JPanel paneHeaderOpciones;
    private javax.swing.JPanel paneMarca;
    private javax.swing.JPanel paneModalArticulo;
    private javax.swing.JPanel paneNombre;
    private javax.swing.JPanel paneOpcionesArticulos;
    private javax.swing.JPanel panePrecio;
    private javax.swing.JPanel paneTablaArticulos;
    private javax.swing.JPanel paneTituloArticulos;
    private javax.swing.JTable tblArticulos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    private void iniComplementLayout() {
        getContentPane().setLayout(new CardLayout());
        
        getContentPane().add(paneContenidoArticulos);
        getContentPane().remove(paneModalArticulo);
        //layaout para el contenido
        FlowLayout flowlayoutContenido = new FlowLayout(FlowLayout.CENTER,10,70);
        paneContenidoArticulos.setLayout(flowlayoutContenido);
            FlowLayout flowlayoutTituloArticulos = new FlowLayout(FlowLayout.LEFT,10,10);
            paneCrudArticulos.setLayout(new BorderLayout());
                paneTituloArticulos.setLayout(flowlayoutTituloArticulos);
                paneCrudArticulos.add(paneTituloArticulos, java.awt.BorderLayout.PAGE_START);
                paneCrudArticulos.add(paneContenedor, java.awt.BorderLayout.CENTER);
                    paneContenedor.setLayout(new BorderLayout());
                    paneContenedor.add(paneOpcionesArticulos, java.awt.BorderLayout.PAGE_START);
                    paneContenedor.add(paneTablaArticulos, java.awt.BorderLayout.CENTER);
                    
                FlowLayout flowlayoutOpArticulos= new FlowLayout(FlowLayout.RIGHT,15,30);
                paneOpcionesArticulos.setLayout(flowlayoutOpArticulos);
                    FlowLayout flowlayoutBoton = new FlowLayout(FlowLayout.CENTER,10,8);
                    paneBuscar.setLayout(new BoxLayout(paneBuscar, BoxLayout.X_AXIS));
                    btnEditar.setLayout(flowlayoutBoton);
                    btnEliminar.setLayout(flowlayoutBoton);
        
        //modal nuevo
        //layout de la ventana  
         paneModalArticulo.setLayout(new BorderLayout());

         paneModalArticulo.add(paneContenidoVentana, java.awt.BorderLayout.CENTER);
         paneModalArticulo.add(paneHeader, java.awt.BorderLayout.PAGE_START);

          //layout de header de la ventana
         paneHeader.setLayout(new BoxLayout(paneHeader, BoxLayout.X_AXIS));

         FlowLayout flowlayoutHeaderOpciones = new FlowLayout(FlowLayout.RIGHT,0,0);
         paneHeaderOpciones.setLayout(flowlayoutHeaderOpciones);
         paneHeader.add(lblHeaderLogo);
         paneHeader.add(lbltitulo);
         paneHeader.add(Box.createHorizontalGlue()); // Espaciador flexible
         paneHeader.add(paneHeaderOpciones);
         //contenido del modal
         
         //contenerdo de los atributos
         paneContenidoVentana.setLayout(new BorderLayout());
         paneContenidoVentana.add(paneAtributosArticulo, java.awt.BorderLayout.CENTER);
         paneContenidoVentana.add(paneBotones, java.awt.BorderLayout.PAGE_END);
         FlowLayout flowlayoutAtributosUsuario = new FlowLayout(FlowLayout.CENTER,10,30);
         paneAtributosArticulo.setLayout(flowlayoutAtributosUsuario);
            //contenedor de los txt y label
            paneNombre.setLayout(new BoxLayout(paneNombre, BoxLayout.Y_AXIS));
                txtnombre.setAlignmentX(LEFT_ALIGNMENT);
                lblnombre.setAlignmentX(LEFT_ALIGNMENT);
                paneNombre.add(lblnombre);     
                paneNombre.add(txtnombre); 
            paneDescripcion.setLayout(new BoxLayout(paneDescripcion, BoxLayout.Y_AXIS));
                txtDescripcion.setAlignmentX(LEFT_ALIGNMENT);
                lblDescripcion.setAlignmentX(LEFT_ALIGNMENT);
                paneDescripcion.add(lblDescripcion);     
                paneDescripcion.add(txtDescripcion); 
            paneCategoria.setLayout(new BoxLayout(paneCategoria, BoxLayout.Y_AXIS));
                cbxCategoria.setAlignmentX(LEFT_ALIGNMENT);
                lblCategoria.setAlignmentX(LEFT_ALIGNMENT);
                paneCategoria.add(lblCategoria);     
                paneCategoria.add(cbxCategoria); 
            paneMarca.setLayout(new BoxLayout(paneMarca, BoxLayout.Y_AXIS));
                cbxMarca.setAlignmentX(LEFT_ALIGNMENT);
                lblMarca.setAlignmentX(LEFT_ALIGNMENT);
                paneMarca.add(lblMarca);     
                paneMarca.add(cbxMarca); 
            panePrecio.setLayout(new BoxLayout(panePrecio, BoxLayout.Y_AXIS));
                txtPrecio.setAlignmentX(LEFT_ALIGNMENT);
                lblPrecio.setAlignmentX(LEFT_ALIGNMENT);
                panePrecio.add(lblPrecio);     
                panePrecio.add(txtPrecio); 
                
        paneAtributosArticulo.add(paneNombre);
        paneAtributosArticulo.add(paneDescripcion);
        paneAtributosArticulo.add(paneCategoria);
        paneAtributosArticulo.add(paneMarca);
        paneAtributosArticulo.remove(panePrecio);
        
        FlowLayout flowlayoutBotones = new FlowLayout(FlowLayout.CENTER,30,10);
        paneBotones.setLayout(flowlayoutBotones);
        btnGuardar.setLayout(new GridBagLayout());
        btnCancelar.setLayout(new GridBagLayout());
    }

    private void iniSize() {
         //tamaño de ventana
        this.setBounds(0,0,1400, 900);
        
        //tamaño del panel de contenido
        paneContenidoArticulos.setPreferredSize(new Dimension( 1, 1));    
            paneCrudArticulos.setPreferredSize(new Dimension( 1000, 650));    
                paneOpcionesArticulos.setPreferredSize(new Dimension( 1000, 100));  
                //paneTablaArticulos.setPreferredSize(new Dimension( 1000, 100));  
                    txtBusqueda.setPreferredSize(new Dimension( 200, 40));
                    btnBuscar.setPreferredSize(new Dimension( 60, 40));
                    btnEditar.setPreferredSize(new Dimension( 200, 40));
                    btnEliminar.setPreferredSize(new Dimension( 200, 40));
        //modal
            //tamaño del panel header
            paneHeader.setPreferredSize(new Dimension( 1, 40));
            lblHeaderLogo.setSize(new Dimension( 40, 40));
            lblCerrarVentana.setPreferredSize(new Dimension( 40, 40));
            
            //tamaño del contenido
            paneAtributosArticulo.setPreferredSize(new Dimension(380,60));
            paneNombre.setPreferredSize(new Dimension(380,60));
            paneDescripcion.setPreferredSize(new Dimension(380,60));
            paneCategoria.setPreferredSize(new Dimension(380,60));
            paneMarca.setPreferredSize(new Dimension(380,60));
            panePrecio.setPreferredSize(new Dimension(380,60));
            
            paneBotones.setPreferredSize(new Dimension(450,100));
            btnGuardar.setPreferredSize(new Dimension(150,40));
            btnCancelar.setPreferredSize(new Dimension(150,40));
    }

    private void iniDiseños() {
        //modal
            //inicaiar imagenes del Header de la ventana.
            redimencionarImagenen(lblHeaderLogo,"/img/logo.png");       
            lblCerrarVentana.setVerticalAlignment(SwingConstants.CENTER);
            lblCerrarVentana.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    public JPanel obtenerPanel(){
        return this.paneContenidoArticulos;
    }
    
    public void redimencionarImagenen(JLabel lblicon,String img){
      // Cargamos la imagen desde un archivo
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource(img));//"/Img/login2.jpg"

        // Ajustamos el tamaño de la imagen al tamaño del JLabel
        Image image = icon.getImage();
        Image scaledImage = image.getScaledInstance(lblicon.getWidth(), lblicon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Establecemos la imagen en el JLabel                
            
        ///labelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/login.jpg"))); 
        lblicon.setIcon(scaledIcon);    
    }
    
    public void NuevoModalArticulo(){
        lbltitulo.setText("Nuevo Articulo");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalArticulo); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,550)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    
    private void EditarModalArticulo(){
        
        lbltitulo.setText("Modificar Articulo");
        JDialog dialo = new JDialog(this, "Mi diálogo", true);
        dialo.setContentPane(paneModalArticulo); // agregamos el contenido del JFrame al JDialog
        dialo.setSize(new Dimension(450,550)); // ajustamos el tamaño del JDialog al del JFrame
        dialo.setUndecorated(true);
        
        dialog= dialo;
    }
    
    private void iniTablaArticulos(){
        tabla = articulosController.ObtenerArticulos();
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("id");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Categoria");
        model.addColumn("Marca");

        for(Map<String, Object> res : tabla){
            Map<String, Object> nomCategoria=articulosController.ObtenerNombreCategoria((Integer)res.get("categoria"));
            Map<String, Object> nomMarca=articulosController.ObtenerNombreMarca((Integer)res.get("marca"));
            model.addRow(new Object[]{res.get("idArticulo"), res.get("nombre"), res.get("descripcion"),nomCategoria.get("nomCategoria"),nomMarca.get("nomMarca")});        
        }
        
        tblArticulos.setModel(model);
        tblArticulos.repaint();
    }
    
    private void iniComboBoxs(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for(Map<String, Object> res : ComboCat){
           model.addElement(res.get("nombre"));      
        }
        cbxCategoria.setModel(model);
        
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        for(Map<String, Object> res : ComboMar){
           model2.addElement(res.get("nombre"));      
        }
        cbxMarca.setModel(model2);
    }
    
    private void Guardar(){
        String nomCategoria=cbxCategoria.getSelectedItem().toString();
        String nomMarca=cbxMarca.getSelectedItem().toString();
        String nombre=txtnombre.getText();
        String descripcion= txtDescripcion.getText();
                
        if(articulosController.registrarArticulo(nomCategoria, nomMarca, nombre, descripcion)){
            ModalNotificar modal = new ModalNotificar("Guardado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
    }
    private void Editar(int id){
        String nomCategoria=cbxCategoria.getSelectedItem().toString();
        String nomMarca=cbxMarca.getSelectedItem().toString();
        String nombre=txtnombre.getText();
        String descripcion= txtDescripcion.getText();
                
        if(articulosController.actualizarArticulo(id,nomCategoria, nomMarca, nombre, descripcion)){
            ModalNotificar modal = new ModalNotificar("Actualizado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }           
        
    }
    private void Eliminar(int id){

        if(articulosController.EliminaArticulo(id)){
            ModalNotificar modal = new ModalNotificar("Eliminado con exito");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }else{
            ModalError modal = new ModalError("ocurrio un error");
            JDialog dialogo = new JDialog(modal, "Mi diálogo", true); // true indica que es modal
            dialogo.setContentPane(modal.getContentPane()); // agregamos el contenido del JFrame al JDialog
            dialogo.setSize(new Dimension(400, 200)); // ajustamos el tamaño del JDialog al del JFrame
            dialogo.setUndecorated(true);
            dialogo.setLocationRelativeTo(null); // centra el dialogo en la pantalla
            dialogo.setVisible(true);
        }      
        
    }
}
